	.align 2
gCryTable::
	cry Cry_Bulbasaur
	cry Cry_Ivysaur
	cry Cry_Venusaur
	cry Cry_Charmander
	cry Cry_Charmeleon
	cry Cry_Charizard
	cry Cry_Squirtle
	cry Cry_Wartortle
	cry Cry_Blastoise
	cry Cry_Caterpie
	cry Cry_Metapod
	cry Cry_Butterfree
	cry Cry_Weedle
	cry Cry_Kakuna
	cry Cry_Beedrill
	cry Cry_Pidgey
	cry Cry_Pidgeotto
	cry Cry_Pidgeot
	cry Cry_Rattata
	cry Cry_Raticate
	cry Cry_Spearow
	cry Cry_Fearow
	cry Cry_Ekans
	cry Cry_Arbok
	cry Cry_Pichu
	cry Cry_Pikachu
	cry Cry_Raichu
	cry Cry_Sandshrew
	cry Cry_Sandslash
	cry Cry_NidoranF
	cry Cry_Nidorina
	cry Cry_Nidoqueen
	cry Cry_NidoranM
	cry Cry_Nidorino
	cry Cry_Nidoking
	cry Cry_Cleffa
	cry Cry_Clefairy
	cry Cry_Clefable
	cry Cry_Vulpix
	cry Cry_Ninetales
	cry Cry_Igglybuff
	cry Cry_Jigglypuff
	cry Cry_Wigglytuff
	cry Cry_Zubat
	cry Cry_Golbat
	cry Cry_Crobat
	cry Cry_Oddish
	cry Cry_Gloom
	cry Cry_Vileplume
	cry Cry_Bellossom
	cry Cry_Paras
	cry Cry_Parasect
	cry Cry_Diglett
	cry Cry_Dugtrio
	cry Cry_Meowth
	cry Cry_Persian
	cry Cry_Psyduck
	cry Cry_Golduck
	cry Cry_Mankey
	cry Cry_Primeape
	cry Cry_Annihilape
	cry Cry_Growlithe
	cry Cry_Arcanine
	cry Cry_Poliwag
	cry Cry_Poliwhirl
	cry Cry_Poliwrath
	cry Cry_Politoed
	cry Cry_Abra
	cry Cry_Kadabra
	cry Cry_Alakazam
	cry Cry_Machop
	cry Cry_Machoke
	cry Cry_Machamp
	cry Cry_Bellsprout
	cry Cry_Weepinbell
	cry Cry_Victreebel
	cry Cry_Tentacool
	cry Cry_Tentacruel
	cry Cry_Geodude
	cry Cry_Graveler
	cry Cry_Golem
	cry Cry_Ponyta
	cry Cry_Rapidash
	cry Cry_Slowpoke
	cry Cry_Slowbro
	cry Cry_Slowking
	cry Cry_Magnemite
	cry Cry_Magneton
	cry Cry_Magnezone
	cry Cry_Doduo
	cry Cry_Dodrio
	cry Cry_Seel
	cry Cry_Dewgong
	cry Cry_Grimer
	cry Cry_Muk
	cry Cry_Shellder
	cry Cry_Cloyster
	cry Cry_Gastly
	cry Cry_Haunter
	cry Cry_Gengar
	cry Cry_Onix
	cry Cry_Steelix
	cry Cry_Drowzee
	cry Cry_Hypno
	cry Cry_Krabby
	cry Cry_Kingler
	cry Cry_Voltorb
	cry Cry_Electrode
	cry Cry_Exeggcute
	cry Cry_Exeggutor
	cry Cry_Cubone
	cry Cry_Marowak
	cry Cry_Tyrogue
	cry Cry_Hitmonlee
	cry Cry_Hitmonchan
	cry Cry_Hitmontop
	cry Cry_Lickitung
	cry Cry_Lickilicky
	cry Cry_Koffing
	cry Cry_Weezing
	cry Cry_Rhyhorn
	cry Cry_Rhydon
	cry Cry_Rhyperior
	cry Cry_Tangela
	cry Cry_Tangrowth
	cry Cry_Kangaskhan
	cry Cry_Horsea
	cry Cry_Seadra
	cry Cry_Kingdra
	cry Cry_Goldeen
	cry Cry_Seaking
	cry Cry_Staryu
	cry Cry_Starmie
	cry Cry_MimeJr
	cry Cry_MrMime
	cry Cry_Scyther
	cry Cry_Scizor
	cry Cry_Kleavor
	cry Cry_Smoochum
	cry Cry_Jynx
	cry Cry_Elekid
	cry Cry_Electabuzz
	cry Cry_Electivire
	cry Cry_Magby
	cry Cry_Magmar
	cry Cry_Magmortar
	cry Cry_Pinsir
	cry Cry_Tauros
	cry Cry_Magikarp
	cry Cry_Gyarados
	cry Cry_Lapras
	cry Cry_Eevee
	cry Cry_Vaporeon
	cry Cry_Jolteon
	cry Cry_Flareon
	cry Cry_Espeon
	cry Cry_Umbreon
	cry Cry_Leafeon
	cry Cry_Glaceon
	cry Cry_Sylveon
	cry Cry_Porygon
	cry Cry_Porygon2
	cry Cry_PorygonZ
	cry Cry_Omanyte
	cry Cry_Omastar
	cry Cry_Kabuto
	cry Cry_Kabutops
	cry Cry_Aerodactyl
	cry Cry_Munchlax
	cry Cry_Snorlax
	cry Cry_Articuno
	cry Cry_Zapdos
	cry Cry_Moltres
	cry Cry_Dratini
	cry Cry_Dragonair
	cry Cry_Dragonite
	cry Cry_Mewtwo
	cry Cry_Mew
	cry Cry_Chikorita
	cry Cry_Bayleef
	cry Cry_Meganium
	cry Cry_Cyndaquil
	cry Cry_Quilava
	cry Cry_Typhlosion
	cry Cry_Totodile
	cry Cry_Croconaw
	cry Cry_Feraligatr
	cry Cry_Sentret
	cry Cry_Furret
	cry Cry_Hoothoot
	cry Cry_Noctowl
	cry Cry_Ledyba
	cry Cry_Ledian
	cry Cry_Spinarak
	cry Cry_Ariados
	cry Cry_Chinchou
	cry Cry_Lanturn
	cry Cry_Togepi
	cry Cry_Togetic
	cry Cry_Togekiss
	cry Cry_Natu
	cry Cry_Xatu
	cry Cry_Mareep
	cry Cry_Flaaffy
	cry Cry_Ampharos
	cry Cry_Azurill
	cry Cry_Marill
	cry Cry_Azumarill
	cry Cry_Bonsly
	cry Cry_Sudowoodo
	cry Cry_Hoppip
	cry Cry_Skiploom
	cry Cry_Jumpluff
	cry Cry_Aipom
	cry Cry_Ambipom
	cry Cry_Sunkern
	cry Cry_Sunflora
	cry Cry_Yanma
	cry Cry_Yanmega
	cry Cry_Wooper
	cry Cry_Quagsire
	cry Cry_Clodsire
	cry Cry_Murkrow
	cry Cry_Honchkrow
.if P_FAMILY_MISDREAVUS == TRUE
	cry Cry_Misdreavus
	cry Cry_Mismagius
.endif @ P_FAMILY_MISDREAVUS
.if P_FAMILY_GIRAFARIG == TRUE
	cry Cry_Girafarig
.endif @ P_FAMILY_GIRAFARIG
.if P_FAMILY_PINECO == TRUE
	cry Cry_Pineco
	cry Cry_Forretress
.endif @ P_FAMILY_PINECO
.if P_FAMILY_GLIGAR == TRUE
	cry Cry_Gligar
	cry Cry_Gliscor
.endif @ P_FAMILY_GLIGAR
.if P_FAMILY_SNUBBULL == TRUE
	cry Cry_Snubbull
	cry Cry_Granbull
.endif @ P_FAMILY_SNUBBULL
.if P_FAMILY_HERACROSS == TRUE
	cry Cry_Heracross
.endif @ P_FAMILY_HERACROSS
.if P_FAMILY_SNEASEL == TRUE
	cry Cry_Sneasel
	cry Cry_Weavile
.if P_HISUIAN_FORMS == TRUE
	cry Cry_Sneasler
.endif @ P_HISUIAN_FORMS
.endif @ P_FAMILY_SNEASEL
.if P_FAMILY_TEDDIURSA == TRUE
	cry Cry_Teddiursa
	cry Cry_Ursaring
.endif @ P_FAMILY_TEDDIURSA
.if P_FAMILY_SLUGMA == TRUE
	cry Cry_Slugma
	cry Cry_Magcargo
.endif @ P_FAMILY_SLUGMA
.if P_FAMILY_SWINUB == TRUE
	cry Cry_Swinub
	cry Cry_Piloswine
	cry Cry_Mamoswine
.endif @ P_FAMILY_SWINUB
.if P_FAMILY_CORSOLA == TRUE
	cry Cry_Corsola
.endif @ P_FAMILY_CORSOLA
.if P_FAMILY_REMORAID == TRUE
	cry Cry_Remoraid
	cry Cry_Octillery
.endif @ P_FAMILY_REMORAID
.if P_FAMILY_DELIBIRD == TRUE
	cry Cry_Delibird
.endif @ P_FAMILY_DELIBIRD
.if P_FAMILY_HOUNDOUR == TRUE
	cry Cry_Houndour
	cry Cry_Houndoom
.endif @ P_FAMILY_HOUNDOUR
.if P_FAMILY_PHANPY == TRUE
	cry Cry_Phanpy
	cry Cry_Donphan
.endif @ P_FAMILY_PHANPY
.if P_FAMILY_STANTLER == TRUE
	cry Cry_Stantler
	cry Cry_Wyrdeer
.endif @ P_FAMILY_STANTLER
.if P_FAMILY_SMEARGLE == TRUE
	cry Cry_Smeargle
.endif @ P_FAMILY_SMEARGLE
.if P_FAMILY_MILTANK == TRUE
	cry Cry_Miltank
.endif @ P_FAMILY_MILTANK
.if P_FAMILY_RAIKOU == TRUE
	cry Cry_Raikou
.endif @ P_FAMILY_RAIKOU
.if P_FAMILY_ENTEI == TRUE
	cry Cry_Entei
.endif @ P_FAMILY_ENTEI
.if P_FAMILY_SUICUNE == TRUE
	cry Cry_Suicune
.endif @ P_FAMILY_SUICUNE
.if P_FAMILY_LARVITAR == TRUE
	cry Cry_Larvitar
	cry Cry_Pupitar
	cry Cry_Tyranitar
.endif @ P_FAMILY_LARVITAR
.if P_FAMILY_LUGIA == TRUE
	cry Cry_Lugia
.endif @ P_FAMILY_LUGIA
.if P_FAMILY_HO_OH == TRUE
	cry Cry_HoOh
.endif @ P_FAMILY_HO_OH
.if P_FAMILY_CELEBI == TRUE
	cry Cry_Celebi
.endif @ P_FAMILY_CELEBI
.if P_FAMILY_TREECKO == TRUE
	cry Cry_Treecko
	cry Cry_Grovyle
	cry Cry_Sceptile
.endif @ P_FAMILY_TREECKO
.if P_FAMILY_TORCHIC == TRUE
	cry Cry_Torchic
	cry Cry_Combusken
	cry Cry_Blaziken
.endif @ P_FAMILY_TORCHIC
.if P_FAMILY_MUDKIP == TRUE
	cry Cry_Mudkip
	cry Cry_Marshtomp
	cry Cry_Swampert
.endif @ P_FAMILY_MUDKIP
.if P_FAMILY_POOCHYENA == TRUE
	cry Cry_Poochyena
	cry Cry_Mightyena
.endif @ P_FAMILY_POOCHYENA
.if P_FAMILY_ZIGZAGOON == TRUE
	cry Cry_Zigzagoon
	cry Cry_Linoone
.endif @ P_FAMILY_ZIGZAGOON
.if P_FAMILY_WURMPLE == TRUE
	cry Cry_Wurmple
	cry Cry_Silcoon
	cry Cry_Beautifly
	cry Cry_Cascoon
	cry Cry_Dustox
.endif @ P_FAMILY_WURMPLE
.if P_FAMILY_LOTAD == TRUE
	cry Cry_Lotad
	cry Cry_Lombre
	cry Cry_Ludicolo
.endif @ P_FAMILY_LOTAD
.if P_FAMILY_SEEDOT == TRUE
	cry Cry_Seedot
	cry Cry_Nuzleaf
	cry Cry_Shiftry
.endif @ P_FAMILY_SEEDOT
.if P_FAMILY_TAILLOW == TRUE
	cry Cry_Taillow
	cry Cry_Swellow
.endif @ P_FAMILY_TAILLOW
.if P_FAMILY_WINGULL == TRUE
	cry Cry_Wingull
	cry Cry_Pelipper
.endif @ P_FAMILY_WINGULL
.if P_FAMILY_RALTS == TRUE
	cry Cry_Ralts
	cry Cry_Kirlia
	cry Cry_Gardevoir
	cry Cry_Gallade
.endif @ P_FAMILY_RALTS
.if P_FAMILY_SURSKIT == TRUE
	cry Cry_Surskit
	cry Cry_Masquerain
.endif @ P_FAMILY_SURSKIT
.if P_FAMILY_SHROOMISH == TRUE
	cry Cry_Shroomish
	cry Cry_Breloom
.endif @ P_FAMILY_SHROOMISH
.if P_FAMILY_SLAKOTH == TRUE
	cry Cry_Slakoth
	cry Cry_Vigoroth
	cry Cry_Slaking
.endif @ P_FAMILY_SLAKOTH
.if P_FAMILY_NINCADA == TRUE
	cry Cry_Nincada
	cry Cry_Ninjask
	cry Cry_Shedinja
.endif @ P_FAMILY_NINCADA
.if P_FAMILY_WHISMUR == TRUE
	cry Cry_Whismur
	cry Cry_Loudred
	cry Cry_Exploud
.endif @ P_FAMILY_WHISMUR
.if P_FAMILY_MAKUHITA == TRUE
	cry Cry_Makuhita
	cry Cry_Hariyama
.endif @ P_FAMILY_MAKUHITA
.if P_FAMILY_NOSEPASS == TRUE
	cry Cry_Nosepass
	cry Cry_Probopass
.endif @ P_FAMILY_NOSEPASS
.if P_FAMILY_SKITTY == TRUE
	cry Cry_Skitty
	cry Cry_Delcatty
.endif @ P_FAMILY_SKITTY
.if P_FAMILY_SABLEYE == TRUE
	cry Cry_Sableye
.endif @ P_FAMILY_SABLEYE
.if P_FAMILY_MAWILE == TRUE
	cry Cry_Mawile
.endif @ P_FAMILY_MAWILE
.if P_FAMILY_ARON == TRUE
	cry Cry_Aron
	cry Cry_Lairon
	cry Cry_Aggron
.endif @ P_FAMILY_ARON
.if P_FAMILY_MEDITITE == TRUE
	cry Cry_Meditite
	cry Cry_Medicham
.endif @ P_FAMILY_MEDITITE
.if P_FAMILY_ELECTRIKE == TRUE
	cry Cry_Electrike
	cry Cry_Manectric
.endif @ P_FAMILY_ELECTRIKE
.if P_FAMILY_PLUSLE == TRUE
	cry Cry_Plusle
.endif @ P_FAMILY_PLUSLE
.if P_FAMILY_MINUN == TRUE
	cry Cry_Minun
.endif @ P_FAMILY_MINUN
.if P_FAMILY_VOLBEAT_ILLUMISE == TRUE
	cry Cry_Volbeat
	cry Cry_Illumise
.endif @ P_FAMILY_VOLBEAT_ILLUMISE
.if P_FAMILY_ROSELIA == TRUE
	cry Cry_Budew
	cry Cry_Roselia
	cry Cry_Roserade
.endif @ P_FAMILY_ROSELIA
.if P_FAMILY_GULPIN == TRUE
	cry Cry_Gulpin
	cry Cry_Swalot
.endif @ P_FAMILY_GULPIN
.if P_FAMILY_CARVANHA == TRUE
	cry Cry_Carvanha
	cry Cry_Sharpedo
.endif @ P_FAMILY_CARVANHA
.if P_FAMILY_WAILMER == TRUE
	cry Cry_Wailmer
	cry Cry_Wailord
.endif @ P_FAMILY_WAILMER
.if P_FAMILY_NUMEL == TRUE
	cry Cry_Numel
	cry Cry_Camerupt
.endif @ P_FAMILY_NUMEL
.if P_FAMILY_TORKOAL == TRUE
	cry Cry_Torkoal
.endif @ P_FAMILY_TORKOAL
.if P_FAMILY_SPOINK == TRUE
	cry Cry_Spoink
	cry Cry_Grumpig
.endif @ P_FAMILY_SPOINK
.if P_FAMILY_SPINDA == TRUE
	cry Cry_Spinda
.endif @ P_FAMILY_SPINDA
.if P_FAMILY_TRAPINCH == TRUE
	cry Cry_Trapinch
	cry Cry_Vibrava
	cry Cry_Flygon
.endif @ P_FAMILY_TRAPINCH
.if P_FAMILY_CACNEA == TRUE
	cry Cry_Cacnea
	cry Cry_Cacturne
.endif @ P_FAMILY_CACNEA
.if P_FAMILY_SWABLU == TRUE
	cry Cry_Swablu
	cry Cry_Altaria
.endif @ P_FAMILY_SWABLU
.if P_FAMILY_ZANGOOSE == TRUE
	cry Cry_Zangoose
.endif @ P_FAMILY_ZANGOOSE
.if P_FAMILY_SEVIPER == TRUE
	cry Cry_Seviper
.endif @ P_FAMILY_SEVIPER
.if P_FAMILY_LUNATONE_SOLROCK == TRUE
	cry Cry_Lunatone
	cry Cry_Solrock
.endif @ P_FAMILY_LUNATONE_SOLROCK
.if P_FAMILY_BARBOACH == TRUE
	cry Cry_Barboach
	cry Cry_Whiscash
.endif @ P_FAMILY_BARBOACH
.if P_FAMILY_CORPHISH == TRUE
	cry Cry_Corphish
	cry Cry_Crawdaunt
.endif @ P_FAMILY_CORPHISH
.if P_FAMILY_BALTOY == TRUE
	cry Cry_Baltoy
	cry Cry_Claydol
.endif @ P_FAMILY_BALTOY
.if P_FAMILY_LILEEP == TRUE
	cry Cry_Lileep
	cry Cry_Cradily
.endif @ P_FAMILY_LILEEP
.if P_FAMILY_ANORITH == TRUE
	cry Cry_Anorith
	cry Cry_Armaldo
.endif @ P_FAMILY_ANORITH
.if P_FAMILY_FEEBAS == TRUE
	cry Cry_Feebas
	cry Cry_Milotic
.endif @ P_FAMILY_FEEBAS
.if P_FAMILY_CASTFORM == TRUE
	cry Cry_Castform
.endif @ P_FAMILY_CASTFORM
.if P_FAMILY_KECLEON == TRUE
	cry Cry_Kecleon
.endif @ P_FAMILY_KECLEON
.if P_FAMILY_SHUPPET == TRUE
	cry Cry_Shuppet
	cry Cry_Banette
.endif @ P_FAMILY_SHUPPET
.if P_FAMILY_DUSKULL == TRUE
	cry Cry_Duskull
	cry Cry_Dusclops
	cry Cry_Dusknoir
.endif @ P_FAMILY_DUSKULL
.if P_FAMILY_TROPIUS == TRUE
	cry Cry_Tropius
.endif @ P_FAMILY_TROPIUS
.if P_FAMILY_CHIMECHO == TRUE
	cry Cry_Chingling
	cry Cry_Chimecho
.endif @ P_FAMILY_CHIMECHO
.if P_FAMILY_ABSOL == TRUE
	cry Cry_Absol
.endif @ P_FAMILY_ABSOL
.if P_FAMILY_SNORUNT == TRUE
	cry Cry_Snorunt
	cry Cry_Glalie
	cry Cry_Froslass
.endif @ P_FAMILY_SNORUNT
.if P_FAMILY_SPHEAL == TRUE
	cry Cry_Spheal
	cry Cry_Sealeo
	cry Cry_Walrein
.endif @ P_FAMILY_SPHEAL
.if P_FAMILY_CLAMPERL == TRUE
	cry Cry_Clamperl
	cry Cry_Huntail
	cry Cry_Gorebyss
.endif @ P_FAMILY_CLAMPERL
.if P_FAMILY_RELICANTH == TRUE
	cry Cry_Relicanth
.endif @ P_FAMILY_RELICANTH
.if P_FAMILY_LUVDISC == TRUE
	cry Cry_Luvdisc
.endif @ P_FAMILY_LUVDISC
.if P_FAMILY_BAGON == TRUE
	cry Cry_Bagon
	cry Cry_Shelgon
	cry Cry_Salamence
.endif @ P_FAMILY_BAGON
.if P_FAMILY_BELDUM == TRUE
	cry Cry_Beldum
	cry Cry_Metang
	cry Cry_Metagross
.endif @ P_FAMILY_BELDUM
.if P_FAMILY_REGIROCK == TRUE
	cry Cry_Regirock
.endif @ P_FAMILY_REGIROCK
.if P_FAMILY_REGICE == TRUE
	cry Cry_Regice
.endif @ P_FAMILY_REGICE
.if P_FAMILY_REGISTEEL == TRUE
	cry Cry_Registeel
.endif @ P_FAMILY_REGISTEEL
.if P_FAMILY_LATIAS == TRUE
	cry Cry_Latias
.endif @ P_FAMILY_LATIAS
.if P_FAMILY_LATIOS == TRUE
	cry Cry_Latios
.endif @ P_FAMILY_LATIOS
.if P_FAMILY_KYOGRE == TRUE
	cry Cry_Kyogre
.endif @ P_FAMILY_KYOGRE
.if P_FAMILY_GROUDON == TRUE
	cry Cry_Groudon
.endif @ P_FAMILY_GROUDON
.if P_FAMILY_RAYQUAZA == TRUE
	cry Cry_Rayquaza
.endif @ P_FAMILY_RAYQUAZA
.if P_FAMILY_JIRACHI == TRUE
	cry Cry_Jirachi
.endif @ P_FAMILY_JIRACHI
.if P_FAMILY_DEOXYS == TRUE
	cry Cry_Deoxys
.endif @ P_FAMILY_DEOXYS
.if P_FAMILY_TURTWIG == TRUE
	cry Cry_Turtwig
	cry Cry_Grotle
	cry Cry_Torterra
.endif @ P_FAMILY_TURTWIG
.if P_FAMILY_CHIMCHAR == TRUE
	cry Cry_Chimchar
	cry Cry_Monferno
	cry Cry_Infernape
.endif @ P_FAMILY_CHIMCHAR
.if P_FAMILY_PIPLUP == TRUE
	cry Cry_Piplup
	cry Cry_Prinplup
	cry Cry_Empoleon
.endif @ P_FAMILY_PIPLUP
.if P_FAMILY_STARLY == TRUE
	cry Cry_Starly
	cry Cry_Staravia
	cry Cry_Staraptor
.endif @ P_FAMILY_STARLY
.if P_FAMILY_BIDOOF == TRUE
	cry Cry_Bidoof
	cry Cry_Bibarel
.endif @ P_FAMILY_BIDOOF
.if P_FAMILY_KRICKETOT == TRUE
	cry Cry_Kricketot
	cry Cry_Kricketune
.endif @ P_FAMILY_KRICKETOT
.if P_FAMILY_SHINX == TRUE
	cry Cry_Shinx
	cry Cry_Luxio
	cry Cry_Luxray
.endif @ P_FAMILY_SHINX
.if P_FAMILY_CRANIDOS == TRUE
	cry Cry_Cranidos
	cry Cry_Rampardos
.endif @ P_FAMILY_CRANIDOS
.if P_FAMILY_SHIELDON == TRUE
	cry Cry_Shieldon
	cry Cry_Bastiodon
.endif @ P_FAMILY_SHIELDON
.if P_FAMILY_BURMY == TRUE
	cry Cry_Burmy
	cry Cry_Wormadam
	cry Cry_Mothim
.endif @ P_FAMILY_BURMY
.if P_FAMILY_COMBEE == TRUE
	cry Cry_Combee
	cry Cry_Vespiquen
.endif @ P_FAMILY_COMBEE
.if P_FAMILY_PACHIRISU == TRUE
	cry Cry_Pachirisu
.endif @ P_FAMILY_PACHIRISU
.if P_FAMILY_BUIZEL == TRUE
	cry Cry_Buizel
	cry Cry_Floatzel
.endif @ P_FAMILY_BUIZEL
.if P_FAMILY_CHERUBI == TRUE
	cry Cry_Cherubi
	cry Cry_Cherrim
.endif @ P_FAMILY_CHERUBI
.if P_FAMILY_SHELLOS == TRUE
	cry Cry_Shellos
	cry Cry_Gastrodon
.endif @ P_FAMILY_SHELLOS
.if P_FAMILY_DRIFLOON == TRUE
	cry Cry_Drifloon
	cry Cry_Drifblim
.endif @ P_FAMILY_DRIFLOON
.if P_FAMILY_BUNEARY == TRUE
	cry Cry_Buneary
	cry Cry_Lopunny
.endif @ P_FAMILY_BUNEARY
.if P_FAMILY_GLAMEOW == TRUE
	cry Cry_Glameow
	cry Cry_Purugly
.endif @ P_FAMILY_GLAMEOW
.if P_FAMILY_STUNKY == TRUE
	cry Cry_Stunky
	cry Cry_Skuntank
.endif @ P_FAMILY_STUNKY
.if P_FAMILY_BRONZOR == TRUE
	cry Cry_Bronzor
	cry Cry_Bronzong
.endif @ P_FAMILY_BRONZOR
.if P_FAMILY_CHATOT == TRUE
	cry Cry_Chatot
.endif @ P_FAMILY_CHATOT
.if P_FAMILY_SPIRITOMB == TRUE
	cry Cry_Spiritomb
.endif @ P_FAMILY_SPIRITOMB
.if P_FAMILY_GIBLE == TRUE
	cry Cry_Gible
	cry Cry_Gabite
	cry Cry_Garchomp
.endif @ P_FAMILY_GIBLE
.if P_FAMILY_RIOLU == TRUE
	cry Cry_Riolu
	cry Cry_Lucario
.endif @ P_FAMILY_RIOLU
.if P_FAMILY_HIPPOPOTAS == TRUE
	cry Cry_Hippopotas
	cry Cry_Hippowdon
.endif @ P_FAMILY_HIPPOPOTAS
.if P_FAMILY_SKORUPI == TRUE
	cry Cry_Skorupi
	cry Cry_Drapion
.endif @ P_FAMILY_SKORUPI
.if P_FAMILY_CROAGUNK == TRUE
	cry Cry_Croagunk
	cry Cry_Toxicroak
.endif @ P_FAMILY_CROAGUNK
.if P_FAMILY_CARNIVINE == TRUE
	cry Cry_Carnivine
.endif @ P_FAMILY_CARNIVINE
.if P_FAMILY_FINNEON == TRUE
	cry Cry_Finneon
	cry Cry_Lumineon
.endif @ P_FAMILY_FINNEON
.if P_FAMILY_SNOVER == TRUE
	cry Cry_Snover
	cry Cry_Abomasnow
.endif @ P_FAMILY_SNOVER
.if P_FAMILY_ROTOM == TRUE
	cry Cry_Rotom
.endif @ P_FAMILY_ROTOM
.if P_FAMILY_HEATRAN == TRUE
	cry Cry_Heatran
.endif @ P_FAMILY_HEATRAN
.if P_FAMILY_REGIGIGAS == TRUE
	cry Cry_Regigigas
.endif @ P_FAMILY_REGIGIGAS
.if P_FAMILY_SNIVY == TRUE
	cry Cry_Snivy
	cry Cry_Servine
	cry Cry_Serperior
.endif @ P_FAMILY_SNIVY
.if P_FAMILY_TEPIG == TRUE
	cry Cry_Tepig
	cry Cry_Pignite
	cry Cry_Emboar
.endif @ P_FAMILY_TEPIG
	cry Cry_Oshawott
	cry Cry_Dewott
	cry Cry_Samurott
.if P_FAMILY_BLITZLE == TRUE
	cry Cry_Blitzle
	cry Cry_Zebstrika
.endif @ P_FAMILY_BLITZLE
.if P_FAMILY_ROGGENROLA == TRUE
	cry Cry_Roggenrola
	cry Cry_Boldore
	cry Cry_Gigalith
.endif @ P_FAMILY_ROGGENROLA
.if P_FAMILY_WOOBAT == TRUE
	cry Cry_Woobat
	cry Cry_Swoobat
.endif @ P_FAMILY_WOOBAT
.if P_FAMILY_DRILBUR == TRUE
	cry Cry_Drilbur
	cry Cry_Excadrill
.endif @ P_FAMILY_DRILBUR
.if P_FAMILY_AUDINO == TRUE
	cry Cry_Audino
.endif @ P_FAMILY_AUDINO
.if P_FAMILY_TIMBURR == TRUE
	cry Cry_Timburr
	cry Cry_Gurdurr
	cry Cry_Conkeldurr
.endif @ P_FAMILY_TIMBURR
.if P_FAMILY_COTTONEE == TRUE
	cry Cry_Cottonee
	cry Cry_Whimsicott
.endif @ P_FAMILY_COTTONEE
.if P_FAMILY_PETILIL == TRUE
	cry Cry_Petilil
	cry Cry_Lilligant
.endif @ P_FAMILY_PETILIL
.if P_FAMILY_SANDILE == TRUE
	cry Cry_Sandile
	cry Cry_Krokorok
	cry Cry_Krookodile
.endif @ P_FAMILY_SANDILE
.if P_FAMILY_DARUMAKA == TRUE
	cry Cry_Darumaka
	cry Cry_Darmanitan
.endif @ P_FAMILY_DARUMAKA
.if P_FAMILY_MARACTUS == TRUE
	cry Cry_Maractus
.endif @ P_FAMILY_MARACTUS
.if P_FAMILY_DWEBBLE == TRUE
	cry Cry_Dwebble
	cry Cry_Crustle
.endif @ P_FAMILY_DWEBBLE
.if P_FAMILY_SCRAGGY == TRUE
	cry Cry_Scraggy
	cry Cry_Scrafty
.endif @ P_FAMILY_SCRAGGY
.if P_FAMILY_SIGILYPH == TRUE
	cry Cry_Sigilyph
.endif @ P_FAMILY_SIGILYPH
.if P_FAMILY_YAMASK == TRUE
	cry Cry_Yamask
	cry Cry_Cofagrigus
.endif @ P_FAMILY_YAMASK
.if P_FAMILY_TIRTOUGA == TRUE
	cry Cry_Tirtouga
	cry Cry_Carracosta
.endif @ P_FAMILY_TIRTOUGA
.if P_FAMILY_ARCHEN == TRUE
	cry Cry_Archen
	cry Cry_Archeops
.endif @ P_FAMILY_ARCHEN
.if P_FAMILY_TRUBBISH == TRUE
	cry Cry_Trubbish
	cry Cry_Garbodor
.endif @ P_FAMILY_TRUBBISH
.if P_FAMILY_ZORUA == TRUE
	cry Cry_Zorua
	cry Cry_Zoroark
.endif @ P_FAMILY_ZORUA
.if P_FAMILY_MINCCINO == TRUE
	cry Cry_Minccino
	cry Cry_Cinccino
.endif @ P_FAMILY_MINCCINO
.if P_FAMILY_GOTHITA == TRUE
	cry Cry_Gothita
	cry Cry_Gothorita
	cry Cry_Gothitelle
.endif @ P_FAMILY_GOTHITA
.if P_FAMILY_SOLOSIS == TRUE
	cry Cry_Solosis
	cry Cry_Duosion
	cry Cry_Reuniclus
.endif @ P_FAMILY_SOLOSIS
.if P_FAMILY_DUCKLETT == TRUE
	cry Cry_Ducklett
	cry Cry_Swanna
.endif @ P_FAMILY_DUCKLETT
.if P_FAMILY_VANILLITE == TRUE
	cry Cry_Vanillite
	cry Cry_Vanillish
	cry Cry_Vanilluxe
.endif @ P_FAMILY_VANILLITE
.if P_FAMILY_KARRABLAST == TRUE
	cry Cry_Karrablast
	cry Cry_Escavalier
.endif @ P_FAMILY_KARRABLAST
.if P_FAMILY_FOONGUS == TRUE
	cry Cry_Foongus
	cry Cry_Amoonguss
.endif @ P_FAMILY_FOONGUS
.if P_FAMILY_FRILLISH == TRUE
	cry Cry_Frillish
	cry Cry_Jellicent
.endif @ P_FAMILY_FRILLISH
.if P_FAMILY_JOLTIK == TRUE
	cry Cry_Joltik
	cry Cry_Galvantula
.endif @ P_FAMILY_JOLTIK
.if P_FAMILY_FERROSEED == TRUE
	cry Cry_Ferroseed
	cry Cry_Ferrothorn
.endif @ P_FAMILY_FERROSEED
.if P_FAMILY_KLINK == TRUE
	cry Cry_Klink
	cry Cry_Klang
	cry Cry_Klinklang
.endif @ P_FAMILY_KLINK
.if P_FAMILY_TYNAMO == TRUE
	cry Cry_Tynamo
	cry Cry_Eelektrik
	cry Cry_Eelektross
.endif @ P_FAMILY_TYNAMO
.if P_FAMILY_ELGYEM == TRUE
	cry Cry_Elgyem
	cry Cry_Beheeyem
.endif @ P_FAMILY_ELGYEM
.if P_FAMILY_LITWICK == TRUE
	cry Cry_Litwick
	cry Cry_Lampent
	cry Cry_Chandelure
.endif @ P_FAMILY_LITWICK
.if P_FAMILY_AXEW == TRUE
	cry Cry_Axew
	cry Cry_Fraxure
	cry Cry_Haxorus
.endif @ P_FAMILY_AXEW
.if P_FAMILY_CUBCHOO == TRUE
	cry Cry_Cubchoo
	cry Cry_Beartic
.endif @ P_FAMILY_CUBCHOO
.if P_FAMILY_CRYOGONAL == TRUE
	cry Cry_Cryogonal
.endif @ P_FAMILY_CRYOGONAL
.if P_FAMILY_GOLETT == TRUE
	cry Cry_Golett
	cry Cry_Golurk
.endif @ P_FAMILY_GOLETT
.if P_FAMILY_PAWNIARD == TRUE
	cry Cry_Pawniard
	cry Cry_Bisharp
.endif @ P_FAMILY_PAWNIARD
.if P_FAMILY_BOUFFALANT == TRUE
	cry Cry_Bouffalant
.endif @ P_FAMILY_BOUFFALANT
.if P_FAMILY_RUFFLET == TRUE
	cry Cry_Rufflet
	cry Cry_Braviary
.endif @ P_FAMILY_RUFFLET
.if P_FAMILY_VULLABY == TRUE
	cry Cry_Vullaby
	cry Cry_Mandibuzz
.endif @ P_FAMILY_VULLABY
.if P_FAMILY_DEINO == TRUE
	cry Cry_Deino
	cry Cry_Zweilous
	cry Cry_Hydreigon
.endif @ P_FAMILY_DEINO
.if P_FAMILY_LARVESTA == TRUE
	cry Cry_Larvesta
	cry Cry_Volcarona
.endif @ P_FAMILY_LARVESTA
.if P_FAMILY_CHESPIN == TRUE
	cry Cry_Chespin
	cry Cry_Quilladin
	cry Cry_Chesnaught
.endif @ P_FAMILY_CHESPIN
	cry Cry_Fennekin
	cry Cry_Braixen
	cry Cry_Delphox
.if P_FAMILY_FROAKIE == TRUE
	cry Cry_Froakie
	cry Cry_Frogadier
	cry Cry_Greninja
.endif @ P_FAMILY_FROAKIE
.if P_FAMILY_BUNNELBY == TRUE
	cry Cry_Bunnelby
	cry Cry_Diggersby
.endif @ P_FAMILY_BUNNELBY
.if P_FAMILY_FLETCHLING == TRUE
	cry Cry_Fletchling
	cry Cry_Fletchinder
	cry Cry_Talonflame
.endif @ P_FAMILY_FLETCHLING
.if P_FAMILY_SCATTERBUG == TRUE
	cry Cry_Scatterbug
	cry Cry_Spewpa
	cry Cry_Vivillon
.endif @ P_FAMILY_SCATTERBUG
.if P_FAMILY_FLABEBE == TRUE
	cry Cry_Flabebe
	cry Cry_Floette
	cry Cry_FloetteEternalFlower
	cry Cry_Florges
.endif @ P_FAMILY_FLABEBE
.if P_FAMILY_SKIDDO == TRUE
	cry Cry_Skiddo
	cry Cry_Gogoat
.endif @ P_FAMILY_SKIDDO
.if P_FAMILY_PANCHAM == TRUE
	cry Cry_Pancham
	cry Cry_Pangoro
.endif @ P_FAMILY_PANCHAM
.if P_FAMILY_ESPURR == TRUE
	cry Cry_Espurr
	cry Cry_Meowstic
.endif @ P_FAMILY_ESPURR
.if P_FAMILY_HONEDGE == TRUE
	cry Cry_Honedge
	cry Cry_Doublade
	cry Cry_Aegislash
.endif @ P_FAMILY_HONEDGE
.if P_FAMILY_TYRUNT == TRUE
	cry Cry_Tyrunt
	cry Cry_Tyrantrum
.endif @ P_FAMILY_TYRUNT
.if P_FAMILY_AMAURA == TRUE
	cry Cry_Amaura
	cry Cry_Aurorus
.endif @ P_FAMILY_AMAURA
.if P_FAMILY_HAWLUCHA == TRUE
	cry Cry_Hawlucha
.endif @ P_FAMILY_HAWLUCHA
.if P_FAMILY_DEDENNE == TRUE
	cry Cry_Dedenne
.endif @ P_FAMILY_DEDENNE
.if P_FAMILY_CARBINK == TRUE
	cry Cry_Carbink
.endif @ P_FAMILY_CARBINK
.if P_FAMILY_GOOMY == TRUE
	cry Cry_Goomy
	cry Cry_Sliggoo
	cry Cry_Goodra
.endif @ P_FAMILY_GOOMY
.if P_FAMILY_PHANTUMP == TRUE
	cry Cry_Phantump
	cry Cry_Trevenant
.endif @ P_FAMILY_PHANTUMP
.if P_FAMILY_DIANCIE == TRUE
	cry Cry_Diancie
.endif @ P_FAMILY_DIANCIE
.if P_FAMILY_ROWLET == TRUE
	cry Cry_Rowlet
	cry Cry_Dartrix
	cry Cry_Decidueye
.endif @ P_FAMILY_ROWLET
.if P_FAMILY_LITTEN == TRUE
	cry Cry_Litten
	cry Cry_Torracat
	cry Cry_Incineroar
.endif @ P_FAMILY_LITTEN
.if P_FAMILY_POPPLIO == TRUE
	cry Cry_Popplio
	cry Cry_Brionne
	cry Cry_Primarina
.endif @ P_FAMILY_POPPLIO
.if P_FAMILY_ROCKRUFF == TRUE
	cry Cry_Rockruff
	cry Cry_LycanrocMidday
	cry Cry_LycanrocMidnight
	cry Cry_LycanrocDusk
.endif @ P_FAMILY_ROCKRUFF
.if P_FAMILY_SANDYGAST == TRUE
	cry Cry_Sandygast
	cry Cry_Palossand
.endif @ P_FAMILY_SANDYGAST
.if P_FAMILY_PYUKUMUKU == TRUE
	cry Cry_Pyukumuku
.endif @ P_FAMILY_PYUKUMUKU
.if P_FAMILY_TYPE_NULL == TRUE
	cry Cry_TypeNull
	cry Cry_Silvally
.endif @ P_FAMILY_TYPE_NULL
.if P_FAMILY_MINIOR == TRUE
	cry Cry_Minior
.endif @ P_FAMILY_MINIOR
.if P_FAMILY_KOMALA == TRUE
	cry Cry_Komala
.endif @ P_FAMILY_KOMALA
.if P_FAMILY_TURTONATOR == TRUE
	cry Cry_Turtonator
.endif @ P_FAMILY_TURTONATOR
.if P_FAMILY_TOGEDEMARU == TRUE
	cry Cry_Togedemaru
.endif @ P_FAMILY_TOGEDEMARU
.if P_FAMILY_MIMIKYU == TRUE
	cry Cry_Mimikyu
.endif @ P_FAMILY_MIMIKYU
.if P_FAMILY_BRUXISH == TRUE
	cry Cry_Bruxish
.endif @ P_FAMILY_BRUXISH
.if P_FAMILY_DRAMPA == TRUE
	cry Cry_Drampa
.endif @ P_FAMILY_DRAMPA
.if P_FAMILY_DHELMISE == TRUE
	cry Cry_Dhelmise
.endif @ P_FAMILY_DHELMISE
.if P_FAMILY_JANGMO_O == TRUE
	cry Cry_JangmoO
	cry Cry_HakamoO
	cry Cry_KommoO
.endif @ P_FAMILY_JANGMO_O
.if P_FAMILY_ROOKIDEE == TRUE
	cry Cry_Rookidee
	cry Cry_Corvisquire
	cry Cry_Corviknight
.endif @ P_FAMILY_ROOKIDEE
.if P_FAMILY_BLIPBUG == TRUE
	cry Cry_Blipbug
	cry Cry_Dottler
	cry Cry_Orbeetle
.endif @ P_FAMILY_BLIPBUG
.if P_FAMILY_WOOLOO == TRUE
	cry Cry_Wooloo
	cry Cry_Dubwool
.endif @ P_FAMILY_WOOLOO
.if P_FAMILY_CHEWTLE == TRUE
	cry Cry_Chewtle
	cry Cry_Drednaw
.endif @ P_FAMILY_CHEWTLE
.if P_FAMILY_YAMPER == TRUE
	cry Cry_Yamper
	cry Cry_Boltund
.endif @ P_FAMILY_YAMPER
.if P_FAMILY_ROLYCOLY == TRUE
	cry Cry_Rolycoly
	cry Cry_Carkol
	cry Cry_Coalossal
.endif @ P_FAMILY_ROLYCOLY
.if P_FAMILY_APPLIN == TRUE
	cry Cry_Applin
	cry Cry_Flapple
	cry Cry_Appletun
.endif @ P_FAMILY_APPLIN
.if P_FAMILY_SILICOBRA == TRUE
	cry Cry_Silicobra
	cry Cry_Sandaconda
.endif @ P_FAMILY_SILICOBRA
.if P_FAMILY_CRAMORANT == TRUE
	cry Cry_Cramorant
.endif @ P_FAMILY_CRAMORANT
.if P_FAMILY_ARROKUDA == TRUE
	cry Cry_Arrokuda
	cry Cry_Barraskewda
.endif @ P_FAMILY_ARROKUDA
.if P_FAMILY_TOXEL == TRUE
	cry Cry_Toxel
	cry Cry_ToxtricityAmped
	cry Cry_ToxtricityLowKey
.endif @ P_FAMILY_TOXEL
.if P_FAMILY_SIZZLIPEDE == TRUE
	cry Cry_Sizzlipede
	cry Cry_Centiskorch
.endif @ P_FAMILY_SIZZLIPEDE
.if P_FAMILY_IMPIDIMP == TRUE
	cry Cry_Impidimp
	cry Cry_Morgrem
	cry Cry_Grimmsnarl
.endif @ P_FAMILY_IMPIDIMP
.if P_FAMILY_PINCURCHIN == TRUE
	cry Cry_Pincurchin
.endif @ P_FAMILY_PINCURCHIN
.if P_FAMILY_SNOM == TRUE
	cry Cry_Snom
	cry Cry_Frosmoth
.endif @ P_FAMILY_SNOM
.if P_FAMILY_CUFANT == TRUE
	cry Cry_Cufant
	cry Cry_Copperajah
.endif @ P_FAMILY_CUFANT
.if P_FAMILY_DURALUDON == TRUE
	cry Cry_Duraludon
.endif @ P_FAMILY_DURALUDON
.if P_FAMILY_DREEPY == TRUE
	cry Cry_Dreepy
	cry Cry_Drakloak
	cry Cry_Dragapult
.endif @ P_FAMILY_DREEPY
.if P_FAMILY_ZACIAN == TRUE
	cry Cry_ZacianHeroOfManyBattles
	cry Cry_ZacianCrownedSword
.endif @ P_FAMILY_ZACIAN
.if P_FAMILY_ZAMAZENTA == TRUE
	cry Cry_ZamazentaHeroOfManyBattles
	cry Cry_ZamazentaCrownedShield
.endif @ P_FAMILY_ZAMAZENTA
.if P_FAMILY_ETERNATUS == TRUE
	cry Cry_Eternatus
	cry Cry_EternatusEternamax
.endif @ P_FAMILY_ETERNATUS
.if P_FAMILY_KUBFU == TRUE
	cry Cry_Kubfu
	cry Cry_UrshifuSingleStrikeStyle
	cry Cry_UrshifuRapidStrikeStyle
.endif @ P_FAMILY_KUBFU
.if P_FAMILY_ZARUDE == TRUE
	cry Cry_Zarude
.endif @ P_FAMILY_ZARUDE
.if P_FAMILY_REGIELEKI == TRUE
	cry Cry_Regieleki
.endif @ P_FAMILY_REGIELEKI
.if P_FAMILY_REGIDRAGO == TRUE
	cry Cry_Regidrago
.endif @ P_FAMILY_REGIDRAGO
.if P_FAMILY_SPRIGATITO == TRUE
	cry Cry_Sprigatito
	cry Cry_Floragato
	cry Cry_Meowscarada
.endif @ P_FAMILY_SPRIGATITO
.if P_FAMILY_FUECOCO == TRUE
	cry Cry_Fuecoco
	cry Cry_Crocalor
	cry Cry_Skeledirge
.endif @ P_FAMILY_FUECOCO
.if P_FAMILY_TAROUNTULA == TRUE
	cry Cry_Tarountula
	cry Cry_Spidops
.endif @ P_FAMILY_TAROUNTULA
.if P_FAMILY_NYMBLE == TRUE
	cry Cry_Nymble
	cry Cry_Lokix
.endif @ P_FAMILY_NYMBLE
.if P_FAMILY_SQUAWKABILLY == TRUE
	cry Cry_Squawkabilly
.endif @ P_FAMILY_SQUAWKABILLY
.if P_FAMILY_CHARCADET == TRUE
	cry Cry_Charcadet
	cry Cry_Armarouge
	cry Cry_Ceruledge
.endif @ P_FAMILY_CHARCADET
.if P_FAMILY_TADBULB == TRUE
	cry Cry_Tadbulb
	cry Cry_Bellibolt
.endif @ P_FAMILY_TADBULB
.if P_FAMILY_WATTREL == TRUE
	cry Cry_Wattrel
	cry Cry_Kilowattrel
.endif @ P_FAMILY_WATTREL
.if P_FAMILY_MASCHIFF == TRUE
	cry Cry_Maschiff
	cry Cry_Mabosstiff
.endif @ P_FAMILY_MASCHIFF
.if P_FAMILY_SHROODLE == TRUE
	cry Cry_Shroodle
	cry Cry_Grafaiai
.endif @ P_FAMILY_SHROODLE
.if P_FAMILY_BRAMBLIN == TRUE
	cry Cry_Bramblin
	cry Cry_Brambleghast
.endif @ P_FAMILY_BRAMBLIN
.if P_FAMILY_TOEDSCOOL == TRUE
	cry Cry_Toedscool
	cry Cry_Toedscruel
.endif @ P_FAMILY_TOEDSCOOL
.if P_FAMILY_KLAWF == TRUE
	cry Cry_Klawf
.endif @ P_FAMILY_KLAWF
.if P_FAMILY_CAPSAKID == TRUE
	cry Cry_Capsakid
	cry Cry_Scovillain
.endif @ P_FAMILY_CAPSAKID
.if P_FAMILY_RELLOR == TRUE
	cry Cry_Rellor
	cry Cry_Rabsca
.endif @ P_FAMILY_RELLOR
.if P_FAMILY_FLITTLE == TRUE
	cry Cry_Flittle
	cry Cry_Espathra
.endif @ P_FAMILY_FLITTLE
.if P_FAMILY_ORTHWORM == TRUE
	cry Cry_Orthworm
.endif @ P_FAMILY_ORTHWORM
.if P_FAMILY_GLIMMET == TRUE
	cry Cry_Glimmet
	cry Cry_Glimmora
.endif @ P_FAMILY_GLIMMET
.if P_FAMILY_GREAVARD == TRUE
	cry Cry_Greavard
	cry Cry_Houndstone
.endif @ P_FAMILY_GREAVARD

	.align 2
gCryTable_Reverse::

	.align 2
