#ifndef GUARD_CONSTANTS_CRIES_H
#define GUARD_CONSTANTS_CRIES_H

enum PokemonCries
{
    CRY_NONE,
    CRY_BULBASAUR,
    CRY_IVYSAUR,
    CRY_VENUSAUR,
    CRY_CHARMANDER,
    CRY_CHARMELEON,
    CRY_CHARIZARD,
    CRY_SQUIRTLE,
    CRY_WARTORTLE,
    CRY_BLASTOISE,
    CRY_CATERPIE,
    CRY_METAPOD,
    CRY_BUTTERFREE,
    CRY_WEEDLE,
    CRY_KAKUNA,
    CRY_BEEDRILL,
    CRY_PIDGEY,
    CRY_PIDGEOTTO,
    CRY_PIDGEOT,
    CRY_RATTATA,
    CRY_RATICATE,
    CRY_SPEAROW,
    CRY_FEAROW,
    CRY_EKANS,
    CRY_ARBOK,
    CRY_PICHU,
    CRY_PIKACHU,
    CRY_RAICHU,
    CRY_SANDSHREW,
    CRY_SANDSLASH,
    CRY_NIDORAN_F,
    CRY_NIDORINA,
    CRY_NIDOQUEEN,
    CRY_NIDORAN_M,
    CRY_NIDORINO,
    CRY_NIDOKING,
    CRY_CLEFFA,
    CRY_CLEFAIRY,
    CRY_CLEFABLE,
    CRY_VULPIX,
    CRY_NINETALES,
    CRY_IGGLYBUFF,
    CRY_JIGGLYPUFF,
    CRY_WIGGLYTUFF,
    CRY_ZUBAT,
    CRY_GOLBAT,
    CRY_CROBAT,
    CRY_ODDISH,
    CRY_GLOOM,
    CRY_VILEPLUME,
    CRY_BELLOSSOM,
    CRY_PARAS,
    CRY_PARASECT,
    CRY_DIGLETT,
    CRY_DUGTRIO,
    CRY_MEOWTH,
    CRY_PERSIAN,
    CRY_PSYDUCK,
    CRY_GOLDUCK,
    CRY_MANKEY,
    CRY_PRIMEAPE,
    CRY_ANNIHILAPE,
    CRY_GROWLITHE,
    CRY_ARCANINE,
    CRY_POLIWAG,
    CRY_POLIWHIRL,
    CRY_POLIWRATH,
    CRY_POLITOED,
    CRY_ABRA,
    CRY_KADABRA,
    CRY_ALAKAZAM,
    CRY_MACHOP,
    CRY_MACHOKE,
    CRY_MACHAMP,
    CRY_BELLSPROUT,
    CRY_WEEPINBELL,
    CRY_VICTREEBEL,
    CRY_TENTACOOL,
    CRY_TENTACRUEL,
    CRY_GEODUDE,
    CRY_GRAVELER,
    CRY_GOLEM,
    CRY_PONYTA,
    CRY_RAPIDASH,
    CRY_SLOWPOKE,
    CRY_SLOWBRO,
    CRY_SLOWKING,
    CRY_MAGNEMITE,
    CRY_MAGNETON,
    CRY_MAGNEZONE,
    CRY_DODUO,
    CRY_DODRIO,
    CRY_SEEL,
    CRY_DEWGONG,
    CRY_GRIMER,
    CRY_MUK,
    CRY_SHELLDER,
    CRY_CLOYSTER,
    CRY_GASTLY,
    CRY_HAUNTER,
    CRY_GENGAR,
    CRY_ONIX,
    CRY_STEELIX,
    CRY_DROWZEE,
    CRY_HYPNO,
    CRY_KRABBY,
    CRY_KINGLER,
    CRY_VOLTORB,
    CRY_ELECTRODE,
    CRY_EXEGGCUTE,
    CRY_EXEGGUTOR,
    CRY_CUBONE,
    CRY_MAROWAK,
    CRY_TYROGUE,
    CRY_HITMONLEE,
    CRY_HITMONCHAN,
    CRY_HITMONTOP,
    CRY_LICKITUNG,
    CRY_LICKILICKY,
    CRY_KOFFING,
    CRY_WEEZING,
    CRY_RHYHORN,
    CRY_RHYDON,
    CRY_RHYPERIOR,
    CRY_TANGELA,
    CRY_TANGROWTH,
    CRY_KANGASKHAN,
    CRY_HORSEA,
    CRY_SEADRA,
    CRY_KINGDRA,
    CRY_GOLDEEN,
    CRY_SEAKING,
    CRY_STARYU,
    CRY_STARMIE,
    CRY_MIME_JR,
    CRY_MR_MIME,
    CRY_SCYTHER,
    CRY_SCIZOR,
    CRY_KLEAVOR,
    CRY_SMOOCHUM,
    CRY_JYNX,
    CRY_ELEKID,
    CRY_ELECTABUZZ,
    CRY_ELECTIVIRE,
    CRY_MAGBY,
    CRY_MAGMAR,
    CRY_MAGMORTAR,
    CRY_PINSIR,
    CRY_TAUROS,
    CRY_MAGIKARP,
    CRY_GYARADOS,
    CRY_LAPRAS,
    CRY_EEVEE,
    CRY_VAPOREON,
    CRY_JOLTEON,
    CRY_FLAREON,
    CRY_ESPEON,
    CRY_UMBREON,
    CRY_LEAFEON,
    CRY_GLACEON,
    CRY_SYLVEON,
    CRY_PORYGON,
    CRY_PORYGON2,
    CRY_PORYGON_Z,
    CRY_OMANYTE,
    CRY_OMASTAR,
    CRY_KABUTO,
    CRY_KABUTOPS,
    CRY_AERODACTYL,
    CRY_MUNCHLAX,
    CRY_SNORLAX,
    CRY_ARTICUNO,
    CRY_ZAPDOS,
    CRY_MOLTRES,
    CRY_DRATINI,
    CRY_DRAGONAIR,
    CRY_DRAGONITE,
    CRY_MEWTWO,
    CRY_MEW,
    CRY_CHIKORITA,
    CRY_BAYLEEF,
    CRY_MEGANIUM,
    CRY_CYNDAQUIL,
    CRY_QUILAVA,
    CRY_TYPHLOSION,
    CRY_TOTODILE,
    CRY_CROCONAW,
    CRY_FERALIGATR,
    CRY_SENTRET,
    CRY_FURRET,
    CRY_HOOTHOOT,
    CRY_NOCTOWL,
    CRY_LEDYBA,
    CRY_LEDIAN,
    CRY_SPINARAK,
    CRY_ARIADOS,
    CRY_CHINCHOU,
    CRY_LANTURN,
    CRY_TOGEPI,
    CRY_TOGETIC,
    CRY_TOGEKISS,
    CRY_NATU,
    CRY_XATU,
    CRY_MAREEP,
    CRY_FLAAFFY,
    CRY_AMPHAROS,
    CRY_AZURILL,
    CRY_MARILL,
    CRY_AZUMARILL,
    CRY_BONSLY,
    CRY_SUDOWOODO,
    CRY_HOPPIP,
    CRY_SKIPLOOM,
    CRY_JUMPLUFF,
    CRY_AIPOM,
    CRY_AMBIPOM,
    CRY_SUNKERN,
    CRY_SUNFLORA,
    CRY_YANMA,
    CRY_YANMEGA,
    CRY_WOOPER,
    CRY_QUAGSIRE,
    CRY_CLODSIRE,
    CRY_MURKROW,
    CRY_HONCHKROW,
    CRY_MISDREAVUS,
    CRY_MISMAGIUS,
    CRY_GIRAFARIG,
    CRY_PINECO,
    CRY_FORRETRESS,
    CRY_GLIGAR,
    CRY_GLISCOR,
    CRY_SNUBBULL,
    CRY_GRANBULL,
    CRY_HERACROSS,
    CRY_SNEASEL,
    CRY_WEAVILE,
    CRY_SNEASLER,
    CRY_TEDDIURSA,
    CRY_URSARING,
    CRY_SLUGMA,
    CRY_MAGCARGO,
    CRY_SWINUB,
    CRY_PILOSWINE,
    CRY_MAMOSWINE,
    CRY_CORSOLA,
    CRY_REMORAID,
    CRY_OCTILLERY,
    CRY_DELIBIRD,
    CRY_HOUNDOUR,
    CRY_HOUNDOOM,
    CRY_PHANPY,
    CRY_DONPHAN,
    CRY_STANTLER,
    CRY_WYRDEER,
    CRY_MILTANK,
    CRY_RAIKOU,
    CRY_ENTEI,
    CRY_SUICUNE,
    CRY_LARVITAR,
    CRY_PUPITAR,
    CRY_TYRANITAR,
    CRY_LUGIA,
    CRY_HO_OH,
    CRY_CELEBI,
#if P_FAMILY_TREECKO
    CRY_TREECKO,
    CRY_GROVYLE,
    CRY_SCEPTILE,
#endif //P_FAMILY_TREECKO
#if P_FAMILY_TORCHIC
    CRY_TORCHIC,
    CRY_COMBUSKEN,
    CRY_BLAZIKEN,
#endif //P_FAMILY_TORCHIC
#if P_FAMILY_MUDKIP
    CRY_MUDKIP,
    CRY_MARSHTOMP,
    CRY_SWAMPERT,
#endif //P_FAMILY_MUDKIP
#if P_FAMILY_POOCHYENA
    CRY_POOCHYENA,
    CRY_MIGHTYENA,
#endif //P_FAMILY_POOCHYENA
#if P_FAMILY_ZIGZAGOON
    CRY_ZIGZAGOON,
    CRY_LINOONE,
#endif //P_FAMILY_ZIGZAGOON
#if P_FAMILY_WURMPLE
    CRY_WURMPLE,
    CRY_SILCOON,
    CRY_BEAUTIFLY,
    CRY_CASCOON,
    CRY_DUSTOX,
#endif //P_FAMILY_WURMPLE
#if P_FAMILY_LOTAD
    CRY_LOTAD,
    CRY_LOMBRE,
    CRY_LUDICOLO,
#endif //P_FAMILY_LOTAD
#if P_FAMILY_SEEDOT
    CRY_SEEDOT,
    CRY_NUZLEAF,
    CRY_SHIFTRY,
#endif //P_FAMILY_SEEDOT
#if P_FAMILY_TAILLOW
    CRY_TAILLOW,
    CRY_SWELLOW,
#endif //P_FAMILY_TAILLOW
#if P_FAMILY_WINGULL
    CRY_WINGULL,
    CRY_PELIPPER,
#endif //P_FAMILY_WINGULL
#if P_FAMILY_RALTS
    CRY_RALTS,
    CRY_KIRLIA,
    CRY_GARDEVOIR,
    CRY_GALLADE,
#endif //P_FAMILY_RALTS
#if P_FAMILY_SURSKIT
    CRY_SURSKIT,
    CRY_MASQUERAIN,
#endif //P_FAMILY_SURSKIT
#if P_FAMILY_SHROOMISH
    CRY_SHROOMISH,
    CRY_BRELOOM,
#endif //P_FAMILY_SHROOMISH
#if P_FAMILY_SLAKOTH
    CRY_SLAKOTH,
    CRY_VIGOROTH,
    CRY_SLAKING,
#endif //P_FAMILY_SLAKOTH
#if P_FAMILY_NINCADA
    CRY_NINCADA,
    CRY_NINJASK,
    CRY_SHEDINJA,
#endif //P_FAMILY_NINCADA
#if P_FAMILY_WHISMUR
    CRY_WHISMUR,
    CRY_LOUDRED,
    CRY_EXPLOUD,
#endif //P_FAMILY_WHISMUR
#if P_FAMILY_MAKUHITA
    CRY_MAKUHITA,
    CRY_HARIYAMA,
#endif //P_FAMILY_MAKUHITA
#if P_FAMILY_NOSEPASS
    CRY_NOSEPASS,
    CRY_PROBOPASS,
#endif //P_FAMILY_NOSEPASS
#if P_FAMILY_SKITTY
    CRY_SKITTY,
    CRY_DELCATTY,
#endif //P_FAMILY_SKITTY
#if P_FAMILY_SABLEYE
    CRY_SABLEYE,
#endif //P_FAMILY_SABLEYE
#if P_FAMILY_MAWILE
    CRY_MAWILE,
#endif //P_FAMILY_MAWILE
#if P_FAMILY_ARON
    CRY_ARON,
    CRY_LAIRON,
    CRY_AGGRON,
#endif //P_FAMILY_ARON
#if P_FAMILY_MEDITITE
    CRY_MEDITITE,
    CRY_MEDICHAM,
#endif //P_FAMILY_MEDITITE
#if P_FAMILY_ELECTRIKE
    CRY_ELECTRIKE,
    CRY_MANECTRIC,
#endif //P_FAMILY_ELECTRIKE
#if P_FAMILY_PLUSLE
    CRY_PLUSLE,
#endif //P_FAMILY_PLUSLE
#if P_FAMILY_MINUN
    CRY_MINUN,
#endif //P_FAMILY_MINUN
#if P_FAMILY_VOLBEAT_ILLUMISE
    CRY_VOLBEAT,
    CRY_ILLUMISE,
#endif //P_FAMILY_VOLBEAT_ILLUMISE
#if P_FAMILY_ROSELIA
    CRY_BUDEW,
    CRY_ROSELIA,
    CRY_ROSERADE,
#endif //P_FAMILY_ROSELIA
#if P_FAMILY_GULPIN
    CRY_GULPIN,
    CRY_SWALOT,
#endif //P_FAMILY_GULPIN
#if P_FAMILY_CARVANHA
    CRY_CARVANHA,
    CRY_SHARPEDO,
#endif //P_FAMILY_CARVANHA
#if P_FAMILY_WAILMER
    CRY_WAILMER,
    CRY_WAILORD,
#endif //P_FAMILY_WAILMER
#if P_FAMILY_NUMEL
    CRY_NUMEL,
    CRY_CAMERUPT,
#endif //P_FAMILY_NUMEL
#if P_FAMILY_TORKOAL
    CRY_TORKOAL,
#endif //P_FAMILY_TORKOAL
#if P_FAMILY_SPOINK
    CRY_SPOINK,
    CRY_GRUMPIG,
#endif //P_FAMILY_SPOINK
#if P_FAMILY_SPINDA
    CRY_SPINDA,
#endif //P_FAMILY_SPINDA
#if P_FAMILY_TRAPINCH
    CRY_TRAPINCH,
    CRY_VIBRAVA,
    CRY_FLYGON,
#endif //P_FAMILY_TRAPINCH
#if P_FAMILY_CACNEA
    CRY_CACNEA,
    CRY_CACTURNE,
#endif //P_FAMILY_CACNEA
#if P_FAMILY_SWABLU
    CRY_SWABLU,
    CRY_ALTARIA,
#endif //P_FAMILY_SWABLU
#if P_FAMILY_ZANGOOSE
    CRY_ZANGOOSE,
#endif //P_FAMILY_ZANGOOSE
#if P_FAMILY_SEVIPER
    CRY_SEVIPER,
#endif //P_FAMILY_SEVIPER
#if P_FAMILY_LUNATONE_SOLROCK
    CRY_LUNATONE,
    CRY_SOLROCK,
#endif //P_FAMILY_LUNATONE_SOLROCK
#if P_FAMILY_BARBOACH
    CRY_BARBOACH,
    CRY_WHISCASH,
#endif //P_FAMILY_BARBOACH
#if P_FAMILY_CORPHISH
    CRY_CORPHISH,
    CRY_CRAWDAUNT,
#endif //P_FAMILY_CORPHISH
#if P_FAMILY_BALTOY
    CRY_BALTOY,
    CRY_CLAYDOL,
#endif //P_FAMILY_BALTOY
#if P_FAMILY_LILEEP
    CRY_LILEEP,
    CRY_CRADILY,
#endif //P_FAMILY_LILEEP
#if P_FAMILY_ANORITH
    CRY_ANORITH,
    CRY_ARMALDO,
#endif //P_FAMILY_ANORITH
#if P_FAMILY_FEEBAS
    CRY_FEEBAS,
    CRY_MILOTIC,
#endif //P_FAMILY_FEEBAS
#if P_FAMILY_CASTFORM
    CRY_CASTFORM,
#endif //P_FAMILY_CASTFORM
#if P_FAMILY_KECLEON
    CRY_KECLEON,
#endif //P_FAMILY_KECLEON
#if P_FAMILY_SHUPPET
    CRY_SHUPPET,
    CRY_BANETTE,
#endif //P_FAMILY_SHUPPET
#if P_FAMILY_DUSKULL
    CRY_DUSKULL,
    CRY_DUSCLOPS,
    CRY_DUSKNOIR,
#endif //P_FAMILY_DUSKULL
#if P_FAMILY_TROPIUS
    CRY_TROPIUS,
#endif //P_FAMILY_TROPIUS
#if P_FAMILY_CHIMECHO
    CRY_CHINGLING,
    CRY_CHIMECHO,
#endif //P_FAMILY_CHIMECHO
#if P_FAMILY_ABSOL
    CRY_ABSOL,
#endif //P_FAMILY_ABSOL
#if P_FAMILY_SNORUNT
    CRY_SNORUNT,
    CRY_GLALIE,
    CRY_FROSLASS,
#endif //P_FAMILY_SNORUNT
#if P_FAMILY_SPHEAL
    CRY_SPHEAL,
    CRY_SEALEO,
    CRY_WALREIN,
#endif //P_FAMILY_SPHEAL
#if P_FAMILY_CLAMPERL
    CRY_CLAMPERL,
    CRY_HUNTAIL,
    CRY_GOREBYSS,
#endif //P_FAMILY_CLAMPERL
#if P_FAMILY_RELICANTH
    CRY_RELICANTH,
#endif //P_FAMILY_RELICANTH
#if P_FAMILY_LUVDISC
    CRY_LUVDISC,
#endif //P_FAMILY_LUVDISC
#if P_FAMILY_BAGON
    CRY_BAGON,
    CRY_SHELGON,
    CRY_SALAMENCE,
#endif //P_FAMILY_BAGON
#if P_FAMILY_BELDUM
    CRY_BELDUM,
    CRY_METANG,
    CRY_METAGROSS,
#endif //P_FAMILY_BELDUM
#if P_FAMILY_REGIROCK
    CRY_REGIROCK,
#endif //P_FAMILY_REGIROCK
#if P_FAMILY_REGICE
    CRY_REGICE,
#endif //P_FAMILY_REGICE
#if P_FAMILY_REGISTEEL
    CRY_REGISTEEL,
#endif //P_FAMILY_REGISTEEL
#if P_FAMILY_LATIAS
    CRY_LATIAS,
#endif //P_FAMILY_LATIAS
#if P_FAMILY_LATIOS
    CRY_LATIOS,
#endif //P_FAMILY_LATIOS
#if P_FAMILY_KYOGRE
    CRY_KYOGRE,
#endif //P_FAMILY_KYOGRE
#if P_FAMILY_GROUDON
    CRY_GROUDON,
#endif //P_FAMILY_GROUDON
#if P_FAMILY_RAYQUAZA
    CRY_RAYQUAZA,
#endif //P_FAMILY_RAYQUAZA
#if P_FAMILY_JIRACHI
    CRY_JIRACHI,
#endif //P_FAMILY_JIRACHI
#if P_FAMILY_DEOXYS
    CRY_DEOXYS,
#endif //P_FAMILY_DEOXYS
#if P_FAMILY_TURTWIG
    CRY_TURTWIG,
    CRY_GROTLE,
    CRY_TORTERRA,
#endif //P_FAMILY_TURTWIG
#if P_FAMILY_CHIMCHAR
    CRY_CHIMCHAR,
    CRY_MONFERNO,
    CRY_INFERNAPE,
#endif //P_FAMILY_CHIMCHAR
#if P_FAMILY_PIPLUP
    CRY_PIPLUP,
    CRY_PRINPLUP,
    CRY_EMPOLEON,
#endif //P_FAMILY_PIPLUP
#if P_FAMILY_STARLY
    CRY_STARLY,
    CRY_STARAVIA,
    CRY_STARAPTOR,
#endif //P_FAMILY_STARLY
#if P_FAMILY_BIDOOF
    CRY_BIDOOF,
    CRY_BIBAREL,
#endif //P_FAMILY_BIDOOF
#if P_FAMILY_KRICKETOT
    CRY_KRICKETOT,
    CRY_KRICKETUNE,
#endif //P_FAMILY_KRICKETOT
#if P_FAMILY_SHINX
    CRY_SHINX,
    CRY_LUXIO,
    CRY_LUXRAY,
#endif //P_FAMILY_SHINX
#if P_FAMILY_CRANIDOS
    CRY_CRANIDOS,
    CRY_RAMPARDOS,
#endif //P_FAMILY_CRANIDOS
#if P_FAMILY_SHIELDON
    CRY_SHIELDON,
    CRY_BASTIODON,
#endif //P_FAMILY_SHIELDON
#if P_FAMILY_BURMY
    CRY_BURMY,
    CRY_WORMADAM,
    CRY_MOTHIM,
#endif //P_FAMILY_BURMY
#if P_FAMILY_COMBEE
    CRY_COMBEE,
    CRY_VESPIQUEN,
#endif //P_FAMILY_COMBEE
#if P_FAMILY_PACHIRISU
    CRY_PACHIRISU,
#endif //P_FAMILY_PACHIRISU
#if P_FAMILY_BUIZEL
    CRY_BUIZEL,
    CRY_FLOATZEL,
#endif //P_FAMILY_BUIZEL
#if P_FAMILY_CHERUBI
    CRY_CHERUBI,
    CRY_CHERRIM,
#endif //P_FAMILY_CHERUBI
#if P_FAMILY_SHELLOS
    CRY_SHELLOS,
    CRY_GASTRODON,
#endif //P_FAMILY_SHELLOS
#if P_FAMILY_DRIFLOON
    CRY_DRIFLOON,
    CRY_DRIFBLIM,
#endif //P_FAMILY_DRIFLOON
#if P_FAMILY_BUNEARY
    CRY_BUNEARY,
    CRY_LOPUNNY,
#endif //P_FAMILY_BUNEARY
#if P_FAMILY_GLAMEOW
    CRY_GLAMEOW,
    CRY_PURUGLY,
#endif //P_FAMILY_GLAMEOW
#if P_FAMILY_STUNKY
    CRY_STUNKY,
    CRY_SKUNTANK,
#endif //P_FAMILY_STUNKY
#if P_FAMILY_BRONZOR
    CRY_BRONZOR,
    CRY_BRONZONG,
#endif //P_FAMILY_BRONZOR
#if P_FAMILY_CHATOT
    CRY_CHATOT,
#endif //P_FAMILY_CHATOT
#if P_FAMILY_SPIRITOMB
    CRY_SPIRITOMB,
#endif //P_FAMILY_SPIRITOMB
#if P_FAMILY_GIBLE
    CRY_GIBLE,
    CRY_GABITE,
    CRY_GARCHOMP,
#endif //P_FAMILY_GIBLE
#if P_FAMILY_RIOLU
    CRY_RIOLU,
    CRY_LUCARIO,
#endif //P_FAMILY_RIOLU
#if P_FAMILY_HIPPOPOTAS
    CRY_HIPPOPOTAS,
    CRY_HIPPOWDON,
#endif //P_FAMILY_HIPPOPOTAS
#if P_FAMILY_SKORUPI
    CRY_SKORUPI,
    CRY_DRAPION,
#endif //P_FAMILY_SKORUPI
#if P_FAMILY_CROAGUNK
    CRY_CROAGUNK,
    CRY_TOXICROAK,
#endif //P_FAMILY_CROAGUNK
#if P_FAMILY_CARNIVINE
    CRY_CARNIVINE,
#endif //P_FAMILY_CARNIVINE
#if P_FAMILY_FINNEON
    CRY_FINNEON,
    CRY_LUMINEON,
#endif //P_FAMILY_FINNEON
#if P_FAMILY_SNOVER
    CRY_SNOVER,
    CRY_ABOMASNOW,
#endif //P_FAMILY_SNOVER
#if P_FAMILY_ROTOM
    CRY_ROTOM,
#endif //P_FAMILY_ROTOM
#if P_FAMILY_HEATRAN
    CRY_HEATRAN,
#endif //P_FAMILY_HEATRAN
#if P_FAMILY_REGIGIGAS
    CRY_REGIGIGAS,
#endif //P_FAMILY_REGIGIGAS
#if P_FAMILY_SNIVY
    CRY_SNIVY,
    CRY_SERVINE,
    CRY_SERPERIOR,
#endif //P_FAMILY_SNIVY
#if P_FAMILY_TEPIG
    CRY_TEPIG,
    CRY_PIGNITE,
    CRY_EMBOAR,
#endif //P_FAMILY_TEPIG
    CRY_OSHAWOTT,
    CRY_DEWOTT,
    CRY_SAMUROTT,
#if P_FAMILY_BLITZLE
    CRY_BLITZLE,
    CRY_ZEBSTRIKA,
#endif //P_FAMILY_BLITZLE
#if P_FAMILY_ROGGENROLA
    CRY_ROGGENROLA,
    CRY_BOLDORE,
    CRY_GIGALITH,
#endif //P_FAMILY_ROGGENROLA
#if P_FAMILY_WOOBAT
    CRY_WOOBAT,
    CRY_SWOOBAT,
#endif //P_FAMILY_WOOBAT
#if P_FAMILY_DRILBUR
    CRY_DRILBUR,
    CRY_EXCADRILL,
#endif //P_FAMILY_DRILBUR
#if P_FAMILY_AUDINO
    CRY_AUDINO,
#endif //P_FAMILY_AUDINO
#if P_FAMILY_TIMBURR
    CRY_TIMBURR,
    CRY_GURDURR,
    CRY_CONKELDURR,
#endif //P_FAMILY_TIMBURR
#if P_FAMILY_COTTONEE
    CRY_COTTONEE,
    CRY_WHIMSICOTT,
#endif //P_FAMILY_COTTONEE
#if P_FAMILY_PETILIL
    CRY_PETILIL,
    CRY_LILLIGANT,
#endif //P_FAMILY_PETILIL
#if P_FAMILY_SANDILE
    CRY_SANDILE,
    CRY_KROKOROK,
    CRY_KROOKODILE,
#endif //P_FAMILY_SANDILE
#if P_FAMILY_DARUMAKA
    CRY_DARUMAKA,
    CRY_DARMANITAN,
#endif //P_FAMILY_DARUMAKA
#if P_FAMILY_MARACTUS
    CRY_MARACTUS,
#endif //P_FAMILY_MARACTUS
#if P_FAMILY_DWEBBLE
    CRY_DWEBBLE,
    CRY_CRUSTLE,
#endif //P_FAMILY_DWEBBLE
#if P_FAMILY_SCRAGGY
    CRY_SCRAGGY,
    CRY_SCRAFTY,
#endif //P_FAMILY_SCRAGGY
#if P_FAMILY_SIGILYPH
    CRY_SIGILYPH,
#endif //P_FAMILY_SIGILYPH
#if P_FAMILY_YAMASK
    CRY_YAMASK,
    CRY_COFAGRIGUS,
#endif //P_FAMILY_YAMASK
#if P_FAMILY_ZORUA
    CRY_ZORUA,
    CRY_ZOROARK,
#endif //P_FAMILY_ZORUA
#if P_FAMILY_MINCCINO
    CRY_MINCCINO,
    CRY_CINCCINO,
#endif //P_FAMILY_MINCCINO
#if P_FAMILY_GOTHITA
    CRY_GOTHITA,
    CRY_GOTHORITA,
    CRY_GOTHITELLE,
#endif //P_FAMILY_GOTHITA
#if P_FAMILY_SOLOSIS
    CRY_SOLOSIS,
    CRY_DUOSION,
    CRY_REUNICLUS,
#endif //P_FAMILY_SOLOSIS
#if P_FAMILY_DUCKLETT
    CRY_DUCKLETT,
    CRY_SWANNA,
#endif //P_FAMILY_DUCKLETT
#if P_FAMILY_VANILLITE
    CRY_VANILLITE,
    CRY_VANILLISH,
    CRY_VANILLUXE,
#endif //P_FAMILY_VANILLITE
#if P_FAMILY_KARRABLAST
    CRY_KARRABLAST,
    CRY_ESCAVALIER,
#endif //P_FAMILY_KARRABLAST
#if P_FAMILY_FOONGUS
    CRY_FOONGUS,
    CRY_AMOONGUSS,
#endif //P_FAMILY_FOONGUS
#if P_FAMILY_FRILLISH
    CRY_FRILLISH,
    CRY_JELLICENT,
#endif //P_FAMILY_FRILLISH
#if P_FAMILY_JOLTIK
    CRY_JOLTIK,
    CRY_GALVANTULA,
#endif //P_FAMILY_JOLTIK
#if P_FAMILY_FERROSEED
    CRY_FERROSEED,
    CRY_FERROTHORN,
#endif //P_FAMILY_FERROSEED
#if P_FAMILY_KLINK
    CRY_KLINK,
    CRY_KLANG,
    CRY_KLINKLANG,
#endif //P_FAMILY_KLINK
#if P_FAMILY_TYNAMO
    CRY_TYNAMO,
    CRY_EELEKTRIK,
    CRY_EELEKTROSS,
#endif //P_FAMILY_TYNAMO
#if P_FAMILY_ELGYEM
    CRY_ELGYEM,
    CRY_BEHEEYEM,
#endif //P_FAMILY_ELGYEM
#if P_FAMILY_LITWICK
    CRY_LITWICK,
    CRY_LAMPENT,
    CRY_CHANDELURE,
#endif //P_FAMILY_LITWICK
#if P_FAMILY_AXEW
    CRY_AXEW,
    CRY_FRAXURE,
    CRY_HAXORUS,
#endif //P_FAMILY_AXEW
#if P_FAMILY_CUBCHOO
    CRY_CUBCHOO,
    CRY_BEARTIC,
#endif //P_FAMILY_CUBCHOO
#if P_FAMILY_CRYOGONAL
    CRY_CRYOGONAL,
#endif //P_FAMILY_CRYOGONAL
#if P_FAMILY_GOLETT
    CRY_GOLETT,
    CRY_GOLURK,
#endif //P_FAMILY_GOLETT
#if P_FAMILY_PAWNIARD
    CRY_PAWNIARD,
    CRY_BISHARP,
#endif //P_FAMILY_PAWNIARD
#if P_FAMILY_BOUFFALANT
    CRY_BOUFFALANT,
#endif //P_FAMILY_BOUFFALANT
#if P_FAMILY_RUFFLET
    CRY_RUFFLET,
    CRY_BRAVIARY,
#endif //P_FAMILY_RUFFLET
#if P_FAMILY_VULLABY
    CRY_VULLABY,
    CRY_MANDIBUZZ,
#endif //P_FAMILY_VULLABY
#if P_FAMILY_DEINO
    CRY_DEINO,
    CRY_ZWEILOUS,
    CRY_HYDREIGON,
#endif //P_FAMILY_DEINO
#if P_FAMILY_LARVESTA
    CRY_LARVESTA,
    CRY_VOLCARONA,
#endif //P_FAMILY_LARVESTA
#if P_FAMILY_CHESPIN
    CRY_CHESPIN,
    CRY_QUILLADIN,
    CRY_CHESNAUGHT,
#endif //P_FAMILY_CHESPIN
    CRY_FENNEKIN,
    CRY_BRAIXEN,
    CRY_DELPHOX,
#if P_FAMILY_FROAKIE
    CRY_FROAKIE,
    CRY_FROGADIER,
    CRY_GRENINJA,
#endif //P_FAMILY_FROAKIE
#if P_FAMILY_BUNNELBY
    CRY_BUNNELBY,
    CRY_DIGGERSBY,
#endif //P_FAMILY_BUNNELBY
#if P_FAMILY_FLETCHLING
    CRY_FLETCHLING,
    CRY_FLETCHINDER,
    CRY_TALONFLAME,
#endif //P_FAMILY_FLETCHLING
#if P_FAMILY_SCATTERBUG
    CRY_SCATTERBUG,
    CRY_SPEWPA,
    CRY_VIVILLON,
#endif //P_FAMILY_SCATTERBUG
#if P_FAMILY_FLABEBE
    CRY_FLABEBE,
    CRY_FLOETTE,
    CRY_FLOETTE_ETERNAL,
    CRY_FLORGES,
#endif //P_FAMILY_FLABEBE
#if P_FAMILY_SKIDDO
    CRY_SKIDDO,
    CRY_GOGOAT,
#endif //P_FAMILY_SKIDDO
#if P_FAMILY_PANCHAM
    CRY_PANCHAM,
    CRY_PANGORO,
#endif //P_FAMILY_PANCHAM
#if P_FAMILY_ESPURR
    CRY_ESPURR,
    CRY_MEOWSTIC,
#endif //P_FAMILY_ESPURR
#if P_FAMILY_HONEDGE
    CRY_HONEDGE,
    CRY_DOUBLADE,
    CRY_AEGISLASH,
#endif //P_FAMILY_HONEDGE
#if P_FAMILY_TYRUNT
    CRY_TYRUNT,
    CRY_TYRANTRUM,
#endif //P_FAMILY_TYRUNT
#if P_FAMILY_AMAURA
    CRY_AMAURA,
    CRY_AURORUS,
#endif //P_FAMILY_AMAURA
#if P_FAMILY_HAWLUCHA
    CRY_HAWLUCHA,
#endif //P_FAMILY_HAWLUCHA
#if P_FAMILY_DEDENNE
    CRY_DEDENNE,
#endif //P_FAMILY_DEDENNE
#if P_FAMILY_CARBINK
    CRY_CARBINK,
#endif //P_FAMILY_CARBINK
#if P_FAMILY_GOOMY
    CRY_GOOMY,
    CRY_SLIGGOO,
    CRY_GOODRA,
#endif //P_FAMILY_GOOMY
#if P_FAMILY_PHANTUMP
    CRY_PHANTUMP,
    CRY_TREVENANT,
#endif //P_FAMILY_PHANTUMP
#if P_FAMILY_DIANCIE
    CRY_DIANCIE,
#endif //P_FAMILY_DIANCIE
#if P_FAMILY_ROWLET
    CRY_ROWLET,
    CRY_DARTRIX,
    CRY_DECIDUEYE,
#endif //P_FAMILY_ROWLET
#if P_FAMILY_LITTEN
    CRY_LITTEN,
    CRY_TORRACAT,
    CRY_INCINEROAR,
#endif //P_FAMILY_LITTEN
#if P_FAMILY_POPPLIO
    CRY_POPPLIO,
    CRY_BRIONNE,
    CRY_PRIMARINA,
#endif //P_FAMILY_POPPLIO
#if P_FAMILY_ROCKRUFF
    CRY_ROCKRUFF,
    CRY_LYCANROC_MIDDAY,
    CRY_LYCANROC_MIDNIGHT,
    CRY_LYCANROC_DUSK,
#endif //P_FAMILY_ROCKRUFF
#if P_FAMILY_SANDYGAST
    CRY_SANDYGAST,
    CRY_PALOSSAND,
#endif //P_FAMILY_SANDYGAST
#if P_FAMILY_MIMIKYU
    CRY_MIMIKYU,
#endif //P_FAMILY_MIMIKYU
#if P_FAMILY_BRUXISH
    CRY_BRUXISH,
#endif //P_FAMILY_BRUXISH
#if P_FAMILY_DRAMPA
    CRY_DRAMPA,
#endif //P_FAMILY_DRAMPA
#if P_FAMILY_DHELMISE
    CRY_DHELMISE,
#endif //P_FAMILY_DHELMISE
#if P_FAMILY_JANGMO_O
    CRY_JANGMO_O,
    CRY_HAKAMO_O,
    CRY_KOMMO_O,
#endif //P_FAMILY_JANGMO_O
#if P_FAMILY_ROOKIDEE
    CRY_ROOKIDEE,
    CRY_CORVISQUIRE,
    CRY_CORVIKNIGHT,
#endif //P_FAMILY_ROOKIDEE
#if P_FAMILY_BLIPBUG
    CRY_BLIPBUG,
    CRY_DOTTLER,
    CRY_ORBEETLE,
#endif //P_FAMILY_BLIPBUG
#if P_FAMILY_WOOLOO
    CRY_WOOLOO,
    CRY_DUBWOOL,
#endif //P_FAMILY_WOOLOO
#if P_FAMILY_TOXEL
    CRY_TOXEL,
    CRY_TOXTRICITY_AMPED,
    CRY_TOXTRICITY_LOW_KEY,
#endif //P_FAMILY_TOXEL
#if P_FAMILY_SIZZLIPEDE
    CRY_SIZZLIPEDE,
    CRY_CENTISKORCH,
#endif //P_FAMILY_SIZZLIPEDE
#if P_FAMILY_IMPIDIMP
    CRY_IMPIDIMP,
    CRY_MORGREM,
    CRY_GRIMMSNARL,
#endif //P_FAMILY_IMPIDIMP
#if P_FAMILY_PINCURCHIN
    CRY_PINCURCHIN,
#endif //P_FAMILY_PINCURCHIN
#if P_FAMILY_SNOM
    CRY_SNOM,
    CRY_FROSMOTH,
#endif //P_FAMILY_SNOM
#if P_FAMILY_CUFANT
    CRY_CUFANT,
    CRY_COPPERAJAH,
#endif //P_FAMILY_CUFANT
#if P_FAMILY_DURALUDON
    CRY_DURALUDON,
#endif //P_FAMILY_DURALUDON
#if P_FAMILY_DREEPY
    CRY_DREEPY,
    CRY_DRAKLOAK,
    CRY_DRAGAPULT,
#endif //P_FAMILY_DREEPY
#if P_FAMILY_ZACIAN
    CRY_ZACIAN_HERO,
    CRY_ZACIAN_CROWNED_SWORD,
#endif //P_FAMILY_ZACIAN
#if P_FAMILY_ZAMAZENTA
    CRY_ZAMAZENTA_HERO,
    CRY_ZAMAZENTA_CROWNED_SHIELD,
#endif //P_FAMILY_ZAMAZENTA
#if P_FAMILY_ETERNATUS
    CRY_ETERNATUS,
    CRY_ETERNATUS_ETERNAMAX,
#endif //P_FAMILY_ETERNATUS
#if P_FAMILY_KUBFU
    CRY_KUBFU,
    CRY_URSHIFU_SINGLE_STRIKE_STYLE,
    CRY_URSHIFU_RAPID_STRIKE_STYLE,
#endif //P_FAMILY_KUBFU
#if P_FAMILY_ZARUDE
    CRY_ZARUDE,
#endif //P_FAMILY_ZARUDE
#if P_FAMILY_REGIELEKI
    CRY_REGIELEKI,
#endif //P_FAMILY_REGIELEKI
#if P_FAMILY_REGIDRAGO
    CRY_REGIDRAGO,
#endif //P_FAMILY_REGIDRAGO
#if P_FAMILY_SPRIGATITO
    CRY_SPRIGATITO,
    CRY_FLORAGATO,
    CRY_MEOWSCARADA,
#endif //P_FAMILY_SPRIGATITO
#if P_FAMILY_FUECOCO
    CRY_FUECOCO,
    CRY_CROCALOR,
    CRY_SKELEDIRGE,
#endif //P_FAMILY_FUECOCO
#if P_FAMILY_TAROUNTULA
    CRY_TAROUNTULA,
    CRY_SPIDOPS,
#endif //P_FAMILY_TAROUNTULA
#if P_FAMILY_NYMBLE
    CRY_NYMBLE,
    CRY_LOKIX,
#endif //P_FAMILY_NYMBLE
#if P_FAMILY_SQUAWKABILLY
    CRY_SQUAWKABILLY,
#endif //P_FAMILY_SQUAWKABILLY
#if P_FAMILY_CHARCADET
    CRY_CHARCADET,
    CRY_ARMAROUGE,
    CRY_CERULEDGE,
#endif //P_FAMILY_CHARCADET
#if P_FAMILY_TADBULB
    CRY_TADBULB,
    CRY_BELLIBOLT,
#endif //P_FAMILY_TADBULB
#if P_FAMILY_WATTREL
    CRY_WATTREL,
    CRY_KILOWATTREL,
#endif //P_FAMILY_WATTREL
#if P_FAMILY_MASCHIFF
    CRY_MASCHIFF,
    CRY_MABOSSTIFF,
#endif //P_FAMILY_MASCHIFF
#if P_FAMILY_SHROODLE
    CRY_SHROODLE,
    CRY_GRAFAIAI,
#endif //P_FAMILY_SHROODLE
#if P_FAMILY_BRAMBLIN
    CRY_BRAMBLIN,
    CRY_BRAMBLEGHAST,
#endif //P_FAMILY_BRAMBLIN
#if P_FAMILY_TOEDSCOOL
    CRY_TOEDSCOOL,
    CRY_TOEDSCRUEL,
#endif //P_FAMILY_TOEDSCOOL
#if P_FAMILY_KLAWF
    CRY_KLAWF,
#endif //P_FAMILY_KLAWF
#if P_FAMILY_CAPSAKID
    CRY_CAPSAKID,
    CRY_SCOVILLAIN,
#endif //P_FAMILY_CAPSAKID
#if P_FAMILY_RELLOR
    CRY_RELLOR,
    CRY_RABSCA,
#endif //P_FAMILY_RELLOR
#if P_FAMILY_FLITTLE
    CRY_FLITTLE,
    CRY_ESPATHRA,
#endif //P_FAMILY_FLITTLE
#if P_FAMILY_ORTHWORM
    CRY_ORTHWORM,
#endif //P_FAMILY_ORTHWORM
#if P_FAMILY_GLIMMET
    CRY_GLIMMET,
    CRY_GLIMMORA,
#endif //P_FAMILY_GLIMMET
#if P_FAMILY_GREAVARD
    CRY_GREAVARD,
    CRY_HOUNDSTONE,
#endif //P_FAMILY_GREAVARD
    CRY_COUNT,
};

#endif // GUARD_CONSTANTS_CRIES_H
