#ifndef GUARD_CONSTANTS_EVENT_BG_H
#define GUARD_CONSTANTS_EVENT_BG_H

enum BgEvents
{
    BG_EVENT_PLAYER_FACING_ANY,
    BG_EVENT_PLAYER_FACING_NORTH,
    BG_EVENT_PLAYER_FACING_SOUTH,
    BG_EVENT_PLAYER_FACING_EAST,
    BG_EVENT_PLAYER_FACING_WEST,
    BG_EVENT_HIDDEN_ITEM,
    BG_EVENT_SECRET_BASE,
};

#endif // GUARD_CONSTANTS_EVENT_BG_H
