#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

enum ObjectEventGraphics
{
    OBJ_EVENT_GFX_BRENDAN_NORMAL,
    OBJ_EVENT_GFX_BRENDAN_MACH_BIKE,
    OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE,
    OBJ_EVENT_GFX_BRENDAN_SURFING,
    OBJ_EVENT_GFX_BRENDAN_UNDERWATER,
    OBJ_EVENT_GFX_BRENDAN_FISHING,
    OBJ_EVENT_GFX_BRENDAN_WATERING,
    OBJ_EVENT_GFX_BRENDAN_DECORATING,
    OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE,
    OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL,
    OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE,
    OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE,
    OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING,
    OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE,
    OBJ_EVENT_GFX_LINK_BRENDAN,
    OBJ_EVENT_GFX_LINK_RS_BRENDAN,
    OBJ_EVENT_GFX_MAY_NORMAL,
    OBJ_EVENT_GFX_MAY_MACH_BIKE,
    OBJ_EVENT_GFX_MAY_ACRO_BIKE,
    OBJ_EVENT_GFX_MAY_SURFING,
    OBJ_EVENT_GFX_MAY_UNDERWATER,
    OBJ_EVENT_GFX_MAY_FISHING,
    OBJ_EVENT_GFX_MAY_WATERING,
    OBJ_EVENT_GFX_MAY_DECORATING,
    OBJ_EVENT_GFX_MAY_FIELD_MOVE,
    OBJ_EVENT_GFX_RIVAL_MAY_NORMAL,
    OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE,
    OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE,
    OBJ_EVENT_GFX_RIVAL_MAY_SURFING,
    OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE,
    OBJ_EVENT_GFX_LINK_MAY,
    OBJ_EVENT_GFX_LINK_RS_MAY,
    OBJ_EVENT_GFX_BOY_1,
    OBJ_EVENT_GFX_BOY_2,
    OBJ_EVENT_GFX_BOY_3,
    OBJ_EVENT_GFX_GIRL_1,
    OBJ_EVENT_GFX_GIRL_2,
    OBJ_EVENT_GFX_GIRL_3,
    OBJ_EVENT_GFX_MAN_1,
    OBJ_EVENT_GFX_MAN_2,
    OBJ_EVENT_GFX_MAN_3,
    OBJ_EVENT_GFX_MAN_4,
    OBJ_EVENT_GFX_MAN_5,
    OBJ_EVENT_GFX_WOMAN_1,
    OBJ_EVENT_GFX_WOMAN_2,
    OBJ_EVENT_GFX_WOMAN_3,
    OBJ_EVENT_GFX_WOMAN_4,
    OBJ_EVENT_GFX_WOMAN_5,
    OBJ_EVENT_GFX_NINJA_BOY,
    OBJ_EVENT_GFX_TWIN,
    OBJ_EVENT_GFX_LITTLE_BOY,
    OBJ_EVENT_GFX_LITTLE_BOY_2,
    OBJ_EVENT_GFX_LITTLE_GIRL,
    OBJ_EVENT_GFX_RICH_BOY,
    OBJ_EVENT_GFX_FAT_MAN,
    OBJ_EVENT_GFX_POKEFAN_M,
    OBJ_EVENT_GFX_POKEFAN_F,
    OBJ_EVENT_GFX_EXPERT_M,
    OBJ_EVENT_GFX_EXPERT_F,
    OBJ_EVENT_GFX_COOK,
    OBJ_EVENT_GFX_LINK_RECEPTIONIST,
    OBJ_EVENT_GFX_OLD_MAN,
    OBJ_EVENT_GFX_OLD_WOMAN,
    OBJ_EVENT_GFX_CAMPER,
    OBJ_EVENT_GFX_PICNICKER,
    OBJ_EVENT_GFX_YOUNGSTER,
    OBJ_EVENT_GFX_BUG_CATCHER,
    OBJ_EVENT_GFX_PSYCHIC_M,
    OBJ_EVENT_GFX_SCHOOL_KID_M,
    OBJ_EVENT_GFX_MANIAC,
    OBJ_EVENT_GFX_HEX_MANIAC,
    OBJ_EVENT_GFX_SWIMMER_M,
    OBJ_EVENT_GFX_SWIMMER_F,
    OBJ_EVENT_GFX_BLACK_BELT,
    OBJ_EVENT_GFX_BEAUTY,
    OBJ_EVENT_GFX_SCIENTIST_1,
    OBJ_EVENT_GFX_SCIENTIST_2,
    OBJ_EVENT_GFX_LASS,
    OBJ_EVENT_GFX_GENTLEMAN,
    OBJ_EVENT_GFX_SAILOR,
    OBJ_EVENT_GFX_FISHERMAN,
    OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M,
    OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F,
    OBJ_EVENT_GFX_TUBER_M,
    OBJ_EVENT_GFX_TUBER_F,
    OBJ_EVENT_GFX_HIKER,
    OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M,
    OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F,
    OBJ_EVENT_GFX_NURSE,
    OBJ_EVENT_GFX_ITEM_BALL,
    OBJ_EVENT_GFX_POKE_BALL,
    OBJ_EVENT_GFX_BREAKABLE_ROCK,
    OBJ_EVENT_GFX_PUSHABLE_BOULDER,
    OBJ_EVENT_GFX_CUTTABLE_TREE,
    OBJ_EVENT_GFX_BERRY_TREE,
    OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES,
    OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES,
    OBJ_EVENT_GFX_PROF_BIRCH,
    OBJ_EVENT_GFX_BIRCHS_BAG,
    OBJ_EVENT_GFX_REPORTER_M,
    OBJ_EVENT_GFX_REPORTER_F,
    OBJ_EVENT_GFX_BARD,
    OBJ_EVENT_GFX_ANABEL,
    OBJ_EVENT_GFX_TUCKER,
    OBJ_EVENT_GFX_GRETA,
    OBJ_EVENT_GFX_SPENSER,
    OBJ_EVENT_GFX_NOLAND,
    OBJ_EVENT_GFX_LUCY,
    OBJ_EVENT_GFX_MART_EMPLOYEE,
    OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN,
    OBJ_EVENT_GFX_TEALA,
    OBJ_EVENT_GFX_MR_BRINEYS_BOAT,
    OBJ_EVENT_GFX_TRUCK,
    OBJ_EVENT_GFX_ARTIST,
    OBJ_EVENT_GFX_CAMERAMAN,
    OBJ_EVENT_GFX_MOVING_BOX,
    OBJ_EVENT_GFX_CABLE_CAR,
    OBJ_EVENT_GFX_DEVON_EMPLOYEE,
    OBJ_EVENT_GFX_AQUA_MEMBER_M,
    OBJ_EVENT_GFX_AQUA_MEMBER_F,
    OBJ_EVENT_GFX_MAGMA_MEMBER_M,
    OBJ_EVENT_GFX_MAGMA_MEMBER_F,
    OBJ_EVENT_GFX_SIDNEY,
    OBJ_EVENT_GFX_PHOEBE,
    OBJ_EVENT_GFX_GLACIA,
    OBJ_EVENT_GFX_DRAKE,
    OBJ_EVENT_GFX_ROXANNE,
    OBJ_EVENT_GFX_BRAWLY,
    OBJ_EVENT_GFX_WATTSON,
    OBJ_EVENT_GFX_FLANNERY,
    OBJ_EVENT_GFX_NORMAN,
    OBJ_EVENT_GFX_WINONA,
    OBJ_EVENT_GFX_LIZA,
    OBJ_EVENT_GFX_TATE,
    OBJ_EVENT_GFX_WALLACE,
    OBJ_EVENT_GFX_STEVEN,
    OBJ_EVENT_GFX_WALLY,
    OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN,
    OBJ_EVENT_GFX_SS_TIDAL,
    OBJ_EVENT_GFX_SUBMARINE_SHADOW,
    OBJ_EVENT_GFX_PICHU_DOLL,
    OBJ_EVENT_GFX_PIKACHU_DOLL,
    OBJ_EVENT_GFX_MARILL_DOLL,
    OBJ_EVENT_GFX_TOGEPI_DOLL,
    OBJ_EVENT_GFX_CYNDAQUIL_DOLL,
    OBJ_EVENT_GFX_CHIKORITA_DOLL,
    OBJ_EVENT_GFX_TOTODILE_DOLL,
    OBJ_EVENT_GFX_JIGGLYPUFF_DOLL,
    OBJ_EVENT_GFX_MEOWTH_DOLL,
    OBJ_EVENT_GFX_CLEFAIRY_DOLL,
    OBJ_EVENT_GFX_DITTO_DOLL,
    OBJ_EVENT_GFX_SMOOCHUM_DOLL,
    OBJ_EVENT_GFX_TREECKO_DOLL,
    OBJ_EVENT_GFX_TORCHIC_DOLL,
    OBJ_EVENT_GFX_MUDKIP_DOLL,
    OBJ_EVENT_GFX_DUSKULL_DOLL,
    OBJ_EVENT_GFX_WYNAUT_DOLL,
    OBJ_EVENT_GFX_BALTOY_DOLL,
    OBJ_EVENT_GFX_KECLEON_DOLL,
    OBJ_EVENT_GFX_AZURILL_DOLL,
    OBJ_EVENT_GFX_SKITTY_DOLL,
    OBJ_EVENT_GFX_SWABLU_DOLL,
    OBJ_EVENT_GFX_GULPIN_DOLL,
    OBJ_EVENT_GFX_LOTAD_DOLL,
    OBJ_EVENT_GFX_SEEDOT_DOLL,
    OBJ_EVENT_GFX_BIG_SNORLAX_DOLL,
    OBJ_EVENT_GFX_BIG_RHYDON_DOLL,
    OBJ_EVENT_GFX_BIG_LAPRAS_DOLL,
    OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL,
    OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL,
    OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL,
    OBJ_EVENT_GFX_BIG_WAILMER_DOLL,
    OBJ_EVENT_GFX_BIG_REGIROCK_DOLL,
    OBJ_EVENT_GFX_BIG_REGICE_DOLL,
    OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL,
    OBJ_EVENT_GFX_PIKA_CUSHION,
    OBJ_EVENT_GFX_ROUND_CUSHION,
    OBJ_EVENT_GFX_KISS_CUSHION,
    OBJ_EVENT_GFX_ZIGZAG_CUSHION,
    OBJ_EVENT_GFX_SPIN_CUSHION,
    OBJ_EVENT_GFX_DIAMOND_CUSHION,
    OBJ_EVENT_GFX_BALL_CUSHION,
    OBJ_EVENT_GFX_GRASS_CUSHION,
    OBJ_EVENT_GFX_FIRE_CUSHION,
    OBJ_EVENT_GFX_WATER_CUSHION,
    OBJ_EVENT_GFX_LIGHT_SPRITE,
    OBJ_EVENT_GFX_OW_MON,
    OBJ_EVENT_GFX_GAMEBOY_KID,
    OBJ_EVENT_GFX_CONTEST_JUDGE,
    OBJ_EVENT_GFX_ARCHIE,
    OBJ_EVENT_GFX_MAXIE,
    OBJ_EVENT_GFX_FOSSIL,
    OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW,
    OBJ_EVENT_GFX_TUBER_M_SWIMMING,
    OBJ_EVENT_GFX_MOM,
    OBJ_EVENT_GFX_JUAN,
    OBJ_EVENT_GFX_SCOTT,
    OBJ_EVENT_GFX_MYSTERY_GIFT_MAN,
    OBJ_EVENT_GFX_TRICK_HOUSE_STATUE,
    OBJ_EVENT_GFX_UNION_ROOM_NURSE,
    OBJ_EVENT_GFX_RED,
    OBJ_EVENT_GFX_LEAF,
    OBJ_EVENT_GFX_DEOXYS_TRIANGLE,
    OBJ_EVENT_GFX_BRANDON,
    OBJ_EVENT_GFX_CYNTHIA,
    NUM_OBJ_EVENT_GFX
};

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0)
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 10)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 11)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 12)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 13)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 14)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 15)

#define OBJ_EVENT_GFX_MON_BASE  512
#define OBJ_EVENT_GFX_SPECIES_BITS 12
#define OBJ_EVENT_GFX_SPECIES_MASK ((1 << OBJ_EVENT_GFX_SPECIES_BITS) - 1)

// Used to call a specific species' follower graphics. Useful for static encounters.
#define OBJ_EVENT_GFX_SPECIES(name)       (SPECIES_##name + OBJ_EVENT_GFX_MON_BASE)
#define OBJ_EVENT_GFX_SPECIES_SHINY(name) (SPECIES_##name + OBJ_EVENT_GFX_MON_BASE + SPECIES_SHINY_TAG)

#define OW_SPECIES(x) (((x)->graphicsId & OBJ_EVENT_GFX_SPECIES_MASK) - OBJ_EVENT_GFX_MON_BASE)
#define OW_FORM(x) ((x)->graphicsId >> OBJ_EVENT_GFX_SPECIES_BITS)

// Whether Object Event is an OW pokemon
#define IS_OW_MON_OBJ(obj) ((obj)->graphicsId >= OBJ_EVENT_GFX_MON_BASE)

#define SHADOW_SIZE_S       0
#define SHADOW_SIZE_M       1
#define SHADOW_SIZE_L       2
#define SHADOW_SIZE_NONE    3   // Originally SHADOW_SIZE_XL, which went unused due to shadowSize in ObjectEventGraphicsInfo being only 2 bits.

#define SHADOW_SIZE_XL_BATTLE_ONLY  SHADOW_SIZE_NONE    // Battle-only definition for XL shadow size.

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2
#define TRACKS_SLITHER    3
#define TRACKS_SPOT       4
#define TRACKS_BUG        5

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255 // Exclusive to FRLG

// Special object event local ids
#define OBJ_EVENT_ID_PLAYER 0xFF
#define OBJ_EVENT_ID_CAMERA 0x7F
#define OBJ_EVENT_ID_FOLLOWER 0xFE

// Object event local ids referenced in C files
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_FARAWAY_ISLAND_MEW 1
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9
#define LOCALID_BATTLE_TOWER_LOBBY_REPORTER 5
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3
#define LOCALID_OLDALE_MART_CLERK 1
#define LOCALID_LAVARIDGE_MART_CLERK 1
#define LOCALID_FALLARBOR_MART_CLERK 1
#define LOCALID_VERDANTURF_MART_CLERK 1
#define LOCALID_PETALBURG_MART_CLERK 1
#define LOCALID_SLATEPORT_MART_CLERK 1
#define LOCALID_MAUVILLE_MART_CLERK 1
#define LOCALID_RUSTBORO_MART_CLERK 1
#define LOCALID_FORTREE_MART_CLERK 1
#define LOCALID_MOSSDEEP_MART_CLERK 1
#define LOCALID_SOOTOPOLIS_MART_CLERK 1
#define LOCALID_BATTLE_FRONTIER_MART_CLERK 1
#define LOCALID_SLATEPORT_ENERGY_GURU 25

enum ObjectEventPalTags
{
    OBJ_EVENT_PAL_TAG_BRENDAN = 4352,
    OBJ_EVENT_PAL_TAG_NPC_1,
    OBJ_EVENT_PAL_TAG_NPC_2,
    OBJ_EVENT_PAL_TAG_NPC_3,
    OBJ_EVENT_PAL_TAG_NPC_4,
    OBJ_EVENT_PAL_TAG_TRUCK,
    OBJ_EVENT_PAL_TAG_MAY,
    OBJ_EVENT_PAL_TAG_MOVING_BOX,
    OBJ_EVENT_PAL_TAG_CABLE_CAR,
    OBJ_EVENT_PAL_TAG_SSTIDAL,
    OBJ_EVENT_PAL_TAG_PLAYER_UNDERWATER,
    OBJ_EVENT_PAL_TAG_SUBMARINE_SHADOW,
    OBJ_EVENT_PAL_TAG_RED_LEAF,
    OBJ_EVENT_PAL_TAG_BIRTH_ISLAND_STONE,
    OBJ_EVENT_PAL_TAG_RS_BRENDAN,
    OBJ_EVENT_PAL_TAG_RS_MAY,
    OBJ_EVENT_PAL_TAG_CYNTHIA,
    OBJ_EVENT_PAL_TAG_BALL_MASTER,
    OBJ_EVENT_PAL_TAG_BALL_ULTRA,
    OBJ_EVENT_PAL_TAG_BALL_GREAT,
    OBJ_EVENT_PAL_TAG_BALL_SAFARI,
    OBJ_EVENT_PAL_TAG_BALL_NET,
    OBJ_EVENT_PAL_TAG_BALL_DIVE,
    OBJ_EVENT_PAL_TAG_BALL_NEST,
    OBJ_EVENT_PAL_TAG_BALL_REPEAT,
    OBJ_EVENT_PAL_TAG_BALL_TIMER,
    OBJ_EVENT_PAL_TAG_BALL_LUXURY,
    OBJ_EVENT_PAL_TAG_BALL_PREMIER,
    OBJ_EVENT_PAL_TAG_BALL_DUSK,
    OBJ_EVENT_PAL_TAG_BALL_HEAL,
    OBJ_EVENT_PAL_TAG_BALL_QUICK,
    OBJ_EVENT_PAL_TAG_BALL_CHERISH,
    OBJ_EVENT_PAL_TAG_BALL_PARK,
    OBJ_EVENT_PAL_TAG_BALL_FAST,
    OBJ_EVENT_PAL_TAG_BALL_LEVEL,
    OBJ_EVENT_PAL_TAG_BALL_LURE,
    OBJ_EVENT_PAL_TAG_BALL_HEAVY,
    OBJ_EVENT_PAL_TAG_BALL_LOVE,
    OBJ_EVENT_PAL_TAG_BALL_FRIEND,
    OBJ_EVENT_PAL_TAG_BALL_MOON,
    OBJ_EVENT_PAL_TAG_BALL_SPORT,
    OBJ_EVENT_PAL_TAG_BALL_DREAM,
    OBJ_EVENT_PAL_TAG_BALL_BEAST,
    OBJ_EVENT_PAL_TAG_LIGHT,
    OBJ_EVENT_PAL_TAG_LIGHT_2,
    OBJ_EVENT_PAL_TAG_EMOTES,
    OBJ_EVENT_PAL_TAG_NEON_LIGHT,
    OBJ_EVENT_PAL_TAG_DYNAMIC,
    OBJ_EVENT_PAL_TAG_WHITE,
    OBJ_EVENT_PAL_TAG_NONE
};

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
