#ifndef GUARD_CONSTANTS_FIELD_TASKS_H
#define GUARD_CONSTANTS_FIELD_TASKS_H

enum StepCB
{
    STEP_CB_DUMMY,
    STEP_CB_ASH,
    STEP_CB_FORTREE_BRIDGE,
    STEP_CB_PACIFIDLOG_BRIDGE,
    STEP_CB_SOOTOPOLIS_ICE,
    STEP_CB_TRUCK,
    STEP_CB_SECRET_BASE,
    STEP_CB_CRACKED_FLOOR,
};

#endif // GUARD_CONSTANTS_FIELD_TASKS_H
