#ifndef GUARD_CONSTANTS_FORM_CHANGE_TYPES_H
#define GUARD_CONSTANTS_FORM_CHANGE_TYPES_H

// FORM_CHANGE_BATTLE_HP_PERCENT param2 arguments
#define HP_HIGHER_THAN      1
#define HP_LOWER_EQ_THAN    2

enum CambiosForma
{
    FORM_CHANGE_TERMINATOR,
    FORM_CHANGE_FAINT,
    FORM_CHANGE_END_BATTLE,
    FORM_CHANGE_BATTLE_SWITCH,
    FORM_CHANGE_BATTLE_HP_PERCENT,
    FORM_CHANGE_BATTLE_WEATHER,
    FORM_CHANGE_ITEM_USE_MULTICHOICE,
};

#endif // GUARD_CONSTANTS_FORM_CHANGE_TYPES_H
