#ifndef GUARD_CONSTANTS_GAME_STAT_H
#define GUARD_CONSTANTS_GAME_STAT_H

//Limpiar las que no se usan, añadir más y utilizarlo como mensaje aleatorio al guardar (máximo 64).

enum GameStats
{
    GAME_STAT_SAVED_GAME,
    GAME_STAT_FIRST_HOF_PLAY_TIME,
    GAME_STAT_STARTED_TRENDS,
    GAME_STAT_PLANTED_BERRIES,
    GAME_STAT_TRADED_BIKES,
    GAME_STAT_STEPS,
    GAME_STAT_GOT_INTERVIEWED,
    GAME_STAT_TOTAL_BATTLES,
    GAME_STAT_WILD_BATTLES,
    GAME_STAT_ENTERED_HOF,
    GAME_STAT_POKEMON_CAPTURES,
    GAME_STAT_FISHING_ENCOUNTERS,
    GAME_STAT_HATCHED_EGGS,
    GAME_STAT_EVOLVED_POKEMON,
    GAME_STAT_USED_POKECENTER,
    GAME_STAT_RESTED_AT_HOME,
    GAME_STAT_ENTERED_SAFARI_ZONE,
    GAME_STAT_USED_CUT,
    GAME_STAT_USED_ROCK_SMASH,
    GAME_STAT_MOVED_SECRET_BASE,
    GAME_STAT_POKEMON_TRADES,
    GAME_STAT_LINK_BATTLE_WINS,
    GAME_STAT_LINK_BATTLE_LOSSES,
    GAME_STAT_LINK_BATTLE_DRAWS,
    GAME_STAT_USED_SPLASH,
    GAME_STAT_USED_STRUGGLE,
    GAME_STAT_SLOT_JACKPOTS,
    GAME_STAT_CONSECUTIVE_ROULETTE_WINS,
    GAME_STAT_ENTERED_BATTLE_TOWER,
    GAME_STAT_BATTLE_TOWER_SINGLES_STREAK,
    GAME_STAT_POKEBLOCKS,
    GAME_STAT_POKEBLOCKS_WITH_FRIENDS,
    GAME_STAT_WON_LINK_CONTEST,
    GAME_STAT_ENTERED_CONTEST,
    GAME_STAT_WON_CONTEST,
    GAME_STAT_SHOPPED,
    GAME_STAT_USED_ITEMFINDER,
    GAME_STAT_GOT_RAINED_ON,
    GAME_STAT_CHECKED_POKEDEX,
    GAME_STAT_RECEIVED_RIBBONS,
    GAME_STAT_JUMPED_DOWN_LEDGES,
    GAME_STAT_WATCHED_TV,
    GAME_STAT_CHECKED_CLOCK,
    GAME_STAT_WON_POKEMON_LOTTERY,
    GAME_STAT_USED_DAYCARE,
    GAME_STAT_RODE_CABLE_CAR,
    GAME_STAT_ENTERED_HOT_SPRINGS,
    GAME_STAT_PLAYED_BERRY_CRUSH,

    NUM_GAME_STATS
};

#endif // GUARD_CONSTANTS_GAME_STAT_H
