#ifndef GUARD_CONSTANTS_PARTY_MENU_H
#define GUARD_CONSTANTS_PARTY_MENU_H

enum Ailments
{
    AILMENT_NONE,
    AILMENT_PSN,
    AILMENT_PRZ,
    AILMENT_SLP,
    AILMENT_FRZ,
    AILMENT_BRN,
    AILMENT_PKRS,
    AILMENT_FNT,
    AILMENT_FRB,
};

enum PartyLayouts
{
    PARTY_LAYOUT_SINGLE,
    PARTY_LAYOUT_DOUBLE,
    PARTY_LAYOUT_MULTI,
    PARTY_LAYOUT_MULTI_SHOWCASE,

    PARTY_LAYOUT_COUNT
};

enum PartyMenuType
{
    PARTY_MENU_TYPE_FIELD,
    PARTY_MENU_TYPE_IN_BATTLE,
    PARTY_MENU_TYPE_CONTEST,
    PARTY_MENU_TYPE_CHOOSE_MON,
    PARTY_MENU_TYPE_CHOOSE_HALF,
    PARTY_MENU_TYPE_MULTI_SHOWCASE,
    PARTY_MENU_TYPE_DAYCARE,
    PARTY_MENU_TYPE_MOVE_RELEARNER,
    PARTY_MENU_TYPE_UNION_ROOM_REGISTER,
    PARTY_MENU_TYPE_UNION_ROOM_TRADE,
    PARTY_MENU_TYPE_MINIGAME,
    PARTY_MENU_TYPE_STORE_PYRAMID_HELD_ITEMS,
};

enum PartyMenuAction
{
    PARTY_ACTION_CHOOSE_MON,
    PARTY_ACTION_SEND_OUT,
    PARTY_ACTION_CANT_SWITCH,
    PARTY_ACTION_USE_ITEM,
    PARTY_ACTION_ABILITY_PREVENTS,
    PARTY_ACTION_GIVE_ITEM,
    PARTY_ACTION_SWITCH,
    PARTY_ACTION_SWITCHING,
    PARTY_ACTION_SOFTBOILED,
    PARTY_ACTION_CHOOSE_AND_CLOSE,
    PARTY_ACTION_MOVE_TUTOR,
    PARTY_ACTION_MINIGAME,
    PARTY_ACTION_CHOOSE_FAINTED_MON,
};

// IDs for DisplayPartyMenuStdMessage, to display the message at the bottom of the party menu
enum PartyMsgs
{
    PARTY_MSG_NONE,
    PARTY_MSG_CHOOSE_MON,
    PARTY_MSG_CHOOSE_MON_OR_CANCEL,
    PARTY_MSG_CHOOSE_MON_AND_CONFIRM,
    PARTY_MSG_MOVE_TO_WHERE,
    PARTY_MSG_TEACH_WHICH_MON,
    PARTY_MSG_USE_ON_WHICH_MON,
    PARTY_MSG_GIVE_TO_WHICH_MON,
    PARTY_MSG_NOTHING_TO_CUT,
    PARTY_MSG_CANT_SURF_HERE,
    PARTY_MSG_ALREADY_SURFING,
    PARTY_MSG_CURRENT_TOO_FAST,
    PARTY_MSG_ENJOY_CYCLING,
    PARTY_MSG_ALREADY_IN_USE,
    PARTY_MSG_CANT_USE_HERE,
    PARTY_MSG_NO_MON_FOR_BATTLE,
    PARTY_MSG_CHOOSE_MON_2,
    PARTY_MSG_NOT_ENOUGH_HP,
    PARTY_MSG_X_MONS_ARE_NEEDED,
    PARTY_MSG_MONS_CANT_BE_SAME,
    PARTY_MSG_NO_SAME_HOLD_ITEMS,
    PARTY_MSG_DO_WHAT_WITH_MON,
    PARTY_MSG_RESTORE_WHICH_MOVE,
    PARTY_MSG_BOOST_PP_WHICH_MOVE,
    PARTY_MSG_DO_WHAT_WITH_ITEM,
    PARTY_MSG_DO_WHAT_WITH_MAIL,
    PARTY_MSG_ALREADY_HOLDING_ONE,
    PARTY_MSG_WHICH_APPLIANCE,
    PARTY_MSG_CHOOSE_SECOND_FUSION,
};

// IDs for DisplayPartyPokemonDescriptionText, to display a message in the party pokemon's box
enum PartyBoxDescs
{
    PARTYBOX_DESC_NO_USE,
    PARTYBOX_DESC_ABLE,
    PARTYBOX_DESC_ABLE_2,
    PARTYBOX_DESC_ABLE_3,
    PARTYBOX_DESC_NOT_ABLE,
    PARTYBOX_DESC_NOT_ABLE_2,
    PARTYBOX_DESC_FIRST,
    PARTYBOX_DESC_SECOND,
    PARTYBOX_DESC_THIRD,
    PARTYBOX_DESC_FOURTH,
    PARTYBOX_DESC_LEARNED,
    PARTYBOX_DESC_HAVE,
    PARTYBOX_DESC_DONT_HAVE,
};

enum SelectWindows
{
    SELECTWINDOW_ACTIONS,
    SELECTWINDOW_ITEM,
    SELECTWINDOW_MAIL,
    SELECTWINDOW_MOVES,
    SELECTWINDOW_CATALOG,
    SELECTWINDOW_ZYGARDECUBE,
};

#define PARTY_NOTHING_CHOSEN        0xFF
#define KEEP_PARTY_LAYOUT           0xFF

#endif // GUARD_CONSTANTS_PARTY_MENU_H
