#ifndef GUARD_CONSTANTS_POKEMON_SPRITE_VISUALIZER_H
#define GUARD_CONSTANTS_POKEMON_SPRITE_VISUALIZER_H

//Defines
#define VISUALIZER_MON_BACK_X 62
#define VISUALIZER_MON_BACK_Y 80
#define VISUALIZER_ICON_X 224
#define VISUALIZER_ICON_Y 144

#define MODIFY_DIGITS_MAX 4
#define MODIFY_DIGITS_ARROW_X 129
#define MODIFY_DIGITS_ARROW1_Y 94
#define MODIFY_DIGITS_ARROW2_Y 113

#define OPTIONS_ARROW_1_X 4
#define OPTIONS_ARROW_2_X 236
#define OPTIONS_ARROW_Y 119

#define GENDER_MALE 0
#define GENDER_FEMALE 1
#define MON_PIC_BACK 0
#define MON_PIC_FRONT 1

//Sprite offset
#define MAX_Y_OFFSET 20

enum SpriteVisualizerWindows
{
    WIN_NAME_NUMBERS,
    WIN_INSTRUCTIONS,
    WIN_BOTTOM_LEFT,
    WIN_BOTTOM_RIGHT,
    WIN_END,
};

#endif // GUARD_CONSTANTS_POKEMON_SPRITE_VISUALIZER_H
