#ifndef GUARD_CONSTANTS_TRAINER_TYPES_H
#define GUARD_CONSTANTS_TRAINER_TYPES_H

enum TrainerTypes
{
    TRAINER_TYPE_NONE,
    TRAINER_TYPE_NORMAL,
    TRAINER_TYPE_SEE_ALL_DIRECTIONS,
    TRAINER_TYPE_BURIED,
};

#endif  // GUARD_CONSTANTS_TRAINER_TYPES_H
