#ifndef GUARD_CONSTANTS_WEATHER_H
#define GUARD_CONSTANTS_WEATHER_H

enum Weathers
{
    WEATHER_NONE,
    WEATHER_SUNNY_CLOUDS,
    WEATHER_SUNNY,
    WEATHER_DROUGHT,
    WEATHER_RAIN,
    WEATHER_RAIN_THUNDERSTORM,
    WEATHER_DOWNPOUR,
    WEATHER_FOG_HORIZONTAL,
    WEATHER_FOG_DIAGONAL,
    WEATHER_VOLCANIC_ASH,
    WEATHER_SANDSTORM,
    WEATHER_UNDERWATER,
    WEATHER_UNDERWATER_BUBBLES,
    WEATHER_SNOW,
    WEATHER_SHADE,
    WEATHER_ABNORMAL,
    WEATHER_ROUTE119_CYCLE,
    WEATHER_ROUTE123_CYCLE,
};

// These are used in maps' coord_weather_event entries.
// They are not a one-to-one mapping with the engine's
// internal weather constants above.
enum CoordsEventWeather
{
    COORD_EVENT_WEATHER_SUNNY_CLOUDS = 1,
    COORD_EVENT_WEATHER_SUNNY,
    COORD_EVENT_WEATHER_RAIN,
    COORD_EVENT_WEATHER_SNOW,
    COORD_EVENT_WEATHER_RAIN_THUNDERSTORM,
    COORD_EVENT_WEATHER_FOG_HORIZONTAL,
    COORD_EVENT_WEATHER_FOG_DIAGONAL,
    COORD_EVENT_WEATHER_VOLCANIC_ASH,
    COORD_EVENT_WEATHER_SANDSTORM,
    COORD_EVENT_WEATHER_SHADE,
    COORD_EVENT_WEATHER_DROUGHT,
    COORD_EVENT_WEATHER_ROUTE119_CYCLE,
    COORD_EVENT_WEATHER_ROUTE123_CYCLE,
};

// These are the "abnormal weather events" that are used
// to find Kyogre and Groudon.
enum AbnormalWeather
{
    ABNORMAL_WEATHER_NONE,

    TERRA_CAVE_LOCATIONS_START,
    ABNORMAL_WEATHER_ROUTE_114_NORTH = TERRA_CAVE_LOCATIONS_START,
    ABNORMAL_WEATHER_ROUTE_114_SOUTH,
    ABNORMAL_WEATHER_ROUTE_115_WEST,
    ABNORMAL_WEATHER_ROUTE_115_EAST,
    ABNORMAL_WEATHER_ROUTE_116_NORTH,
    ABNORMAL_WEATHER_ROUTE_116_SOUTH,
    ABNORMAL_WEATHER_ROUTE_118_EAST,
    ABNORMAL_WEATHER_ROUTE_118_WEST,

    MARINE_CAVE_LOCATIONS_START,
    ABNORMAL_WEATHER_ROUTE_105_NORTH = MARINE_CAVE_LOCATIONS_START,
    ABNORMAL_WEATHER_ROUTE_105_SOUTH,
    ABNORMAL_WEATHER_ROUTE_125_WEST,
    ABNORMAL_WEATHER_ROUTE_125_EAST,
    ABNORMAL_WEATHER_ROUTE_127_NORTH,
    ABNORMAL_WEATHER_ROUTE_127_SOUTH,
    ABNORMAL_WEATHER_ROUTE_129_WEST,
    ABNORMAL_WEATHER_ROUTE_129_EAST,

    ABNORMAL_WEATHER_LOCATIONS,
    TERRA_CAVE_LOCATIONS = ABNORMAL_WEATHER_ROUTE_118_WEST,
    MARINE_CAVE_LOCATIONS = ABNORMAL_WEATHER_ROUTE_129_EAST - MARINE_CAVE_LOCATIONS_START + 1,
};

#endif // GUARD_CONSTANTS_WEATHER_H
