Questionnaire_Text_FillOut::
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"

Questionnaire_Text_ThankYou::
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY GIFT.\p"
	.string "From now on, you should be\n"
	.string "receiving MYSTERY GIFTS!$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY EVENT.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY EVENT.$"
